package com.bandlab.metro.station.entry

import com.bandlab.metro.station.graph.MetroStationIds
import com.bandlab.metro.station.utils.ClassIds
import com.bandlab.metro.station.utils.resolveParentScopeClassIdFromAnnotation
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionHintExtension
import dev.zacsweers.metro.compiler.api.fir.MetroContributionHintExtension.ContributionHint
import dev.zacsweers.metro.compiler.compat.CompatContext
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId

/**
 * Implements [MetroContributionHintExtension] to generate cross-module contribution hint files
 * for `FeatureExtension.Factory` and `ExtensionFactoryContribution` interfaces generated by
 * [StationEntryFir].
 *
 * These hint files allow Metro's `ContributionHintFirGenerator` to discover contributions from
 * dependency modules during downstream compilation.
 */
public class StationEntryHintExtension(private val session: FirSession) : MetroContributionHintExtension {

    private val predicate = MetroStationIds.stationEntryPredicate

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(predicate)
    }

    override fun getContributionHints(): List<ContributionHint> {
        return session.predicateBasedProvider
            .getSymbolsByPredicate(predicate)
            .filterIsInstance<FirRegularClassSymbol>()
            .flatMap { classSymbol ->
                val parentScope = resolveParentScopeClassId(classSymbol)
                val factoryClassId = classSymbol.classId
                    .createNestedClassId(MetroStationIds.featureExtensionName)
                    .createNestedClassId(MetroStationIds.nestedFactoryName)
                val extensionFactoryContributionClassId = classSymbol.classId
                    .createNestedClassId(MetroStationIds.extensionFactoryContributionName)

                // Always emit both hints. If ExtensionFactoryContribution wasn't generated
                // (non-Fragment types), Metro's hint resolver safely skips non-existent classes.
                listOf(
                    ContributionHint(contributingClassId = factoryClassId, scope = parentScope),
                    ContributionHint(contributingClassId = extensionFactoryContributionClassId, scope = parentScope),
                )
            }
    }

    private fun resolveParentScopeClassId(owner: FirRegularClassSymbol): ClassId {
        return resolveParentScopeClassIdFromAnnotation(
            owner,
            MetroStationIds.stationEntry,
            session,
            ClassIds.appScope
        )
    }

    public class Factory : MetroContributionHintExtension.Factory {
        override fun create(
            session: FirSession,
            options: MetroOptions,
            compatContext: CompatContext,
        ): MetroContributionHintExtension {
            return StationEntryHintExtension(session)
        }
    }
}
