package com.bandlab.metro.station.entry

import com.bandlab.metro.station.utils.generateProvideBaseTypeBody
import com.bandlab.metro.station.utils.generateProvideParamBody
import com.bandlab.metro.station.utils.generateProvideParamFlowBody
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid
import com.bandlab.metro.station.graph.MetroStationIds as Ids

/**
 * IR extension that generates code for the graph extension generated by [StationEntryFir].
 */
public class StationEntryIr : IrGenerationExtension {

    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(StationEntryIrTransformer(pluginContext))
    }
}

private class StationEntryIrTransformer(private val pluginContext: IrPluginContext) :
    IrElementTransformerVoid() {

    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != StationEntryFir.Key
        ) {
            return super.visitSimpleFunction(declaration)
        }
        if (declaration.body != null) return super.visitSimpleFunction(declaration)
        when (declaration.name) {
            Ids.provideParamName -> generateProvideParamBody(pluginContext, declaration)
            Ids.provideBaseTypeName -> generateProvideBaseTypeBody(pluginContext, declaration)
            Ids.provideFactoryName -> generateProvideFactoryBody(declaration)
            Ids.provideParamFlowName -> generateProvideParamFlowBody(pluginContext, declaration)
        }
        return super.visitSimpleFunction(declaration)
    }

    /**
     * Generates: `return factory`
     */
    private fun generateProvideFactoryBody(declaration: IrSimpleFunction) {
        val factoryParameter = declaration.parameters.first { it.kind == IrParameterKind.Regular }

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(irGet(factoryParameter))
        }
    }
}
