package com.bandlab.metro.extensions.component

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.types.classOrNull
import org.jetbrains.kotlin.ir.util.getPropertyGetter
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid

/**
 * Ir extension that generates code for the dependency graph generated by [ContributesComponentFir].
 */
public class ContributesComponentIr: IrGenerationExtension {

    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(ContributesComponentIrTransformer(pluginContext))
    }
}

private class ContributesComponentIrTransformer(private val pluginContext: IrPluginContext) :
    IrElementTransformerVoid() {

    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != ContributesComponentFir.Key
        ) {
            return super.visitSimpleFunction(declaration)
        }
        if (declaration.body != null) return super.visitSimpleFunction(declaration)
        if (declaration.name == ContributesComponentIds.provideParamName) {
            generateProvidesBody(declaration)
        }
        return super.visitSimpleFunction(declaration)
    }

    /**
     * Generates: `return feature.params`
     */
    private fun generateProvidesBody(declaration: IrSimpleFunction) {
        val featureParameter = declaration.parameters.first { it.kind == IrParameterKind.Regular }
        val featureType = featureParameter.type
        val featureClass = featureType.classOrNull?.owner ?: return
        val paramsGetterSymbol = featureClass.getPropertyGetter("params") ?: return

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(
                irCall(paramsGetterSymbol).apply {
                    dispatchReceiver = irGet(featureParameter)
                }
            )
        }
    }
}
