package com.bandlab.metro.extensions.component

import com.bandlab.metro.extensions.utils.ClassIds
import com.fueledbycaffeine.autoservice.AutoService
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.scopes.getSingleClassifier
import org.jetbrains.kotlin.fir.scopes.impl.declaredMemberScope
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId

/**
 * Implements [MetroContributionExtension] to tell Metro's `ContributedInterfaceSupertypeGenerator`
 * about contributions from our generated `FeatureServiceProvider` interfaces.
 *
 * This is necessary because Metro's predicate-based provider only discovers source declarations and
 * declarations generated by generators that registered the `@ContributesTo` predicate. Our
 * `FeatureServiceProvider` is generated by [ContributesComponentFir] (which registers a
 * predicate for `@ContributesComponent`), so Metro's in-compilation discovery doesn't see it.
 */
public class ContributesComponentMetroExtension(private val session: FirSession) : MetroContributionExtension {

    private val predicate = ContributesComponentIds.predicate

    private val annotatedClasses by lazy {
        session.predicateBasedProvider
            .getSymbolsByPredicate(predicate)
            .filterIsInstance<FirRegularClassSymbol>()
            .toList()
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(predicate)
    }

    override fun getContributions(
        scopeClassId: ClassId,
        typeResolverFactory: MetroFirTypeResolver.Factory,
    ): List<MetroContributionExtension.Contribution> {
        // FeatureServiceProvider is always contributed to AppScope.
        if (scopeClassId != ClassIds.appScope) return emptyList()

        return annotatedClasses.mapNotNull { parentSymbol ->
            val contributionInterfaceClassId =
                parentSymbol.classId.createNestedClassId(ContributesComponentIds.featureServiceProviderName)

            val contributionSymbol = session.symbolProvider.getClassLikeSymbolByClassId(contributionInterfaceClassId)
                as? FirRegularClassSymbol ?: return@mapNotNull null

            // Access the declared member scope to trigger Metro's FIR generator, which creates the
            // MetroContribution nested class inside our FeatureServiceProvider. Without this, Metro
            // wouldn't see our contribution.
            val scope = contributionSymbol.declaredMemberScope(session, memberRequiredPhase = null)
            val metroContributionName =
                scope.getClassifierNames().firstOrNull { it.identifier.startsWith("MetroContributionTo") }
                    ?: return@mapNotNull null

            val metroContributionSymbol = scope.getSingleClassifier(metroContributionName) as? FirRegularClassSymbol
                ?: return@mapNotNull null

            MetroContributionExtension.Contribution(
                supertype = metroContributionSymbol.defaultType(),
                replaces = emptyList(),
                originClassId = parentSymbol.classId,
            )
        }
    }

    @AutoService
    public class Factory : MetroContributionExtension.Factory {
        override fun create(
            session: FirSession,
            options: MetroOptions,
            compatContext: CompatContext,
        ): MetroContributionExtension {
            return ContributesComponentMetroExtension(session)
        }
    }
}
