package com.bandlab.metro.extensions.component

import com.bandlab.metro.extensions.utils.asName
import com.bandlab.metro.extensions.utils.toCallableId
import org.jetbrains.kotlin.backend.common.extensions.DeclarationFinder
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.builders.*
import org.jetbrains.kotlin.ir.builders.declarations.buildFun
import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.expressions.IrClassReference
import org.jetbrains.kotlin.ir.expressions.IrStatementOrigin
import org.jetbrains.kotlin.ir.expressions.IrTypeOperator
import org.jetbrains.kotlin.ir.expressions.impl.IrFunctionExpressionImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl
import org.jetbrains.kotlin.ir.types.classOrNull
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import com.bandlab.metro.extensions.component.ContributesComponentIds as Ids
import com.bandlab.metro.extensions.utils.ClassIds as MetroClassIds

/**
 * Ir extension that generates code for the dependency graph generated by [ContributesComponentFir].
 *
 * Note: This class is largely AI-generated, please make sure you have a clear kdoc for each declaration.
 */
public class ContributesComponentIr : IrGenerationExtension {

    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(ContributesComponentIrTransformer(pluginContext))
    }
}

private class ContributesComponentIrTransformer(private val pluginContext: IrPluginContext) :
    IrElementTransformerVoid() {

    private val finder: DeclarationFinder = pluginContext.finderForBuiltins()

    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != ContributesComponentFir.Key
        ) {
            return super.visitSimpleFunction(declaration)
        }
        if (declaration.body != null) return super.visitSimpleFunction(declaration)
        when (declaration.name) {
            Ids.provideParamName -> generateProvideParamBody(declaration)
            Ids.provideBaseTypeName -> generateProvideBaseTypeBody(declaration)
            Ids.provideParamFlowName -> generateProvideParamFlowBody(declaration)
            Ids.resolveName -> generateResolveBody(declaration)
        }
        return super.visitSimpleFunction(declaration)
    }

    override fun visitProperty(declaration: IrProperty): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != ContributesComponentFir.Key
        ) {
            return super.visitProperty(declaration)
        }
        when (declaration.name) {
            Ids.graphPropertyName -> generateGraphPropertyBody(declaration)
            Ids.graphCreatorPropertyName -> generateGraphCreatorPropertyBody(declaration)
        }
        return super.visitProperty(declaration)
    }

    /**
     * Generates the graph property getter body with lazy initialization:
     * ```
     * = lazy {
     *     createGraphFactory<FeatureGraph.Factory>()
     *       .create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies)
     * }
     * ```
     */
    private fun generateGraphPropertyBody(declaration: IrProperty) {
        val getter = declaration.getter ?: return
        val backingField = declaration.backingField ?: return
        val parentClass = declaration.parent as? IrClass ?: return
        val thisReceiver = parentClass.thisReceiver ?: return
        val getterThisReceiver = getter.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Find FeatureGraph.Factory nested class
        val featureGraphClass = parentClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return
        val factoryClass = featureGraphClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return

        // Reference createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactoryCallableId = MetroClassIds.createGraphFactory.toCallableId()
        val createGraphFactoryFunctions = finder.findFunctions(createGraphFactoryCallableId)
        val createGraphFactorySymbol = createGraphFactoryFunctions.firstOrNull() ?: return

        // Reference resolveServiceProvider()
        val resolveServiceProviderCallableId = Ids.resolveServiceProvider.toCallableId()
        val resolveServiceProviderFunctions = finder.findFunctions(resolveServiceProviderCallableId)
        val resolveServiceProviderSymbol = resolveServiceProviderFunctions.firstOrNull() ?: return

        // Reference EmptyExtraDependencies object
        val emptyExtraDepsClass = finder.findClass(Ids.emptyExtraDependencies) ?: return

        // Reference kotlin.lazy
        val lazyCallableId = CallableId(FqName("kotlin"), "lazy".asName())
        val lazyFunctions = finder.findFunctions(lazyCallableId)
        // Pick the lazy(LazyThreadSafetyMode, () -> T) or lazy(() -> T) overload
        val lazySymbol =
            lazyFunctions.firstOrNull { it.owner.parameters.count { p -> p.kind == IrParameterKind.Regular } == 1 }
                ?: return

        val graphType = declaration.getter!!.returnType

        // Fix backing field type to Lazy<FeatureGraph> since it stores the lazy delegate
        val lazyClassId = ClassId(FqName("kotlin"), "Lazy".asName())
        val lazyClassSymbol = finder.findClass(lazyClassId) ?: return
        val lazyType = lazyClassSymbol.typeWith(graphType)
        backingField.type = lazyType

        // Build the backing field initializer: lazy { createGraphFactory<Factory>().create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies) }
        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)

        backingField.initializer = pluginContext.irFactory.createExpressionBody(
            builder.irCall(lazySymbol).apply {
                // Set type argument T = graphType
                typeArguments[0] = graphType

                // Build the lambda: { createGraphFactory<Factory>().create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies) }
                val lambdaReturnType = graphType
                val lambdaType = pluginContext.irBuiltIns.functionN(0).typeWith(lambdaReturnType)

                val lambdaFunction = pluginContext.irFactory.buildFun {
                    name = org.jetbrains.kotlin.name.Name.special("<anonymous>")
                    returnType = lambdaReturnType
                    visibility = org.jetbrains.kotlin.descriptors.DescriptorVisibilities.LOCAL
                    origin = IrDeclarationOrigin.LOCAL_FUNCTION_FOR_LAMBDA
                }.apply {
                    parent = backingField

                    body = DeclarationIrBuilder(pluginContext, symbol).irBlockBody {
                        // createGraphFactory<FeatureGraph.Factory>()
                        val createFactoryCall = irCall(createGraphFactorySymbol).apply {
                            typeArguments[0] = factoryClass.symbol.typeWith()
                        }

                        // .create(this, resolveServiceProvider(), EmptyExtraDependencies)
                        val factoryClassOwner = factoryClass.superTypes
                            .mapNotNull { it.classOrNull?.owner }
                            .find { it.functions.any { f -> f.name == Ids.createName } }
                            ?: factoryClass

                        val createFunction = factoryClassOwner.functions.first { it.name == Ids.createName }

                        // Find FeatureServiceProvider type for resolveServiceProvider<T>()
                        val featureServiceProviderClass = parentClass.declarations
                            .filterIsInstance<IrClass>()
                            .find { it.name == Ids.featureServiceProviderName }
                        val serviceProviderType = featureServiceProviderClass?.symbol?.typeWith()

                        // Find applicationContext property getter from ContextWrapper
                        val contextWrapperClassId = ClassId(FqName("android.content"), "ContextWrapper".asName())
                        val contextWrapperClass = finder.findClass(contextWrapperClassId)?.owner
                            ?: error("Cannot find android.content.ContextWrapper class")
                        val applicationContextGetter = contextWrapperClass.getSimpleFunction("getApplicationContext")
                            ?: error("Cannot find 'applicationContext' property getter on ContextWrapper")

                        val createCall = irCall(createFunction).apply {
                            dispatchReceiver = createFactoryCall
                            // feature = this
                            arguments[1] = irGet(thisReceiver)
                            // serviceProvider = applicationContext.resolveServiceProvider()
                            arguments[2] = irCall(resolveServiceProviderSymbol).apply {
                                // type argument T = FeatureServiceProvider
                                if (serviceProviderType != null) {
                                    typeArguments[0] = serviceProviderType
                                }
                                // extension receiver = applicationContext
                                arguments[0] = irCall(applicationContextGetter).apply {
                                    dispatchReceiver = irGet(thisReceiver)
                                }
                            }
                            // extraDependencies = EmptyExtraDependencies
                            arguments[3] = irGetObject(emptyExtraDepsClass)
                        }

                        +irReturn(createCall)
                    }
                }

                val lambdaExpression = IrFunctionExpressionImpl(
                    startOffset = UNDEFINED_OFFSET,
                    endOffset = UNDEFINED_OFFSET,
                    type = lambdaType,
                    function = lambdaFunction,
                    origin = IrStatementOrigin.LAMBDA,
                )

                // arguments[0] = lambda (the regular parameter)
                arguments[lazySymbol.owner.parameters.indexOfFirst { it.kind == IrParameterKind.Regular }] =
                    lambdaExpression
            }
        )

        // Reference Lazy.value getter
        val lazyClass = finder.findClass(lazyClassId) ?: return
        val lazyValueGetter = lazyClass.owner.properties.first { it.name.asString() == "value" }.getter!!

        // Generate getter body: return backingField.value
        getter.body = DeclarationIrBuilder(pluginContext, getter.symbol).irBlockBody {
            val getLazy = irGetField(irGet(getterThisReceiver), backingField)
            val getValue = irCall(lazyValueGetter).apply {
                dispatchReceiver = getLazy
            }
            +irReturn(getValue)
        }
    }

    /**
     * Generates the graph property getter body with lazy initialization:
     * ```
     * = lazy {
     *     graphCreator(
     *         context, // Context, or ComponentActivity
     *         createGraphFactory<OpenRevisionDialogGraph.Factory>(),
     *         EmptyExtraDependencies // Or actual extra dependencies if it's presented in the annotation
     *     )
     * }
     * ```
     */
    private fun generateGraphCreatorPropertyBody(declaration: IrProperty) {
        val getter = declaration.getter ?: return
        val backingField = declaration.backingField ?: return
        val parentClass = declaration.parent as? IrClass ?: return
        val getterThisReceiver = getter.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Find FeatureGraph.Factory nested class
        val featureGraphClass = parentClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return
        val factoryClass = featureGraphClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return

        // Find context parameter from the class constructor
        val contextClass = finder.findClass(Ids.context)
        val componentActivityClass = finder.findClass(Ids.componentActivity)

        val primaryConstructor = parentClass.declarations
            .filterIsInstance<IrConstructor>()
            .firstOrNull { it.isPrimary }
            ?: error("Cannot find primary constructor for ${parentClass.name}")

        val contextParam = primaryConstructor.parameters
            .filter { it.kind == IrParameterKind.Regular }
            .find { param ->
                val paramClassSymbol = param.type.classOrNull
                paramClassSymbol == contextClass || paramClassSymbol == componentActivityClass
            } ?: error("Cannot find Context or ComponentActivity parameter in constructor of ${parentClass.name}")

        // Reference createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactoryCallableId = MetroClassIds.createGraphFactory.toCallableId()
        val createGraphFactoryFunctions = finder.findFunctions(createGraphFactoryCallableId)
        val createGraphFactorySymbol = createGraphFactoryFunctions.firstOrNull() ?: return

        // Reference graphCreator extension function
        val graphCreatorCallableId = Ids.pageGraphCreatorExtension.toCallableId()
        val graphCreatorFunctions = finder.findFunctions(graphCreatorCallableId)
        val graphCreatorSymbol = graphCreatorFunctions.firstOrNull() ?: return

        // Determine extraDependencies: check annotation for extraDependencies parameter
        // If present, find matching constructor parameter; otherwise use EmptyExtraDependencies
        val emptyExtraDepsClass = finder.findClass(Ids.emptyExtraDependencies) ?: return

        // Read the @ContributesComponent annotation from the parent class
        val contributesComponentAnnotation = parentClass.annotations.find { annotation ->
            annotation.type.classOrNull?.owner?.name == Ids.contributesComponent.shortClassName
        }

        // Check if extraDependencies is specified (not null/Nothing)
        val extraDepsClassRef = contributesComponentAnnotation?.let { annotation ->
            // Find the extraDependencies parameter index in the full parameters list
            val extraDepsParamIndex = annotation.symbol.owner.parameters
                .indexOfFirst { it.kind == IrParameterKind.Regular && it.name == Ids.extraDependenciesName }
                .takeIf { it >= 0 }
            extraDepsParamIndex?.let { idx ->
                val arg = annotation.arguments[idx] ?: return@let null
                // Filter out Nothing::class (means no extra dependencies specified)
                val classRef = arg as? IrClassReference
                if (classRef != null && classRef.classType == pluginContext.irBuiltIns.nothingType) {
                    null
                } else {
                    arg
                }
            }
        }

        // Determine if we have a non-trivial extraDependencies type (non-null means it was specified)
        val extraDepsRefType = (extraDepsClassRef as? IrClassReference)?.classType
        val extraDepsConstructorParam = if (extraDepsRefType != null) {
            primaryConstructor.parameters
                .filter { it.kind == IrParameterKind.Regular }
                .find { param -> param.type.classOrNull == extraDepsRefType.classOrNull }
        } else null
        val hasExtraDeps = extraDepsConstructorParam != null

        // Find the extra dependencies expression to pass
        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)

        backingField.initializer = pluginContext.irFactory.createExpressionBody(
            builder.irCall(graphCreatorSymbol).apply {
                val graphCreatorOwner = graphCreatorSymbol.owner
                val thisReceiver = parentClass.thisReceiver ?: return

                // Extension receiver = this (the Page)
                val extensionReceiverIndex = graphCreatorOwner.parameters.indexOfFirst { it.kind == IrParameterKind.ExtensionReceiver }
                if (extensionReceiverIndex >= 0) {
                    arguments[extensionReceiverIndex] = builder.irGet(thisReceiver)
                }

                // Type arguments: Root, ServiceProvider, ExtraDependencies, Graph
                val featureServiceProviderClass = parentClass.declarations
                    .filterIsInstance<IrClass>()
                    .find { it.name == Ids.featureServiceProviderName }
                val serviceProviderType = featureServiceProviderClass?.symbol?.typeWith()

                val graphType = featureGraphClass.symbol.typeWith()

                typeArguments[0] = parentClass.symbol.typeWith() // Root
                if (serviceProviderType != null) typeArguments[1] = serviceProviderType // ServiceProvider

                // Determine extraDependencies type
                val extraDepsType = if (hasExtraDeps) {
                    extraDepsConstructorParam.type
                } else {
                    emptyExtraDepsClass.typeWith()
                }
                typeArguments[2] = extraDepsType // ExtraDependencies
                typeArguments[3] = graphType // Graph

                // Regular parameters: context, factory, extraDependencies
                val regularParams = graphCreatorOwner.parameters.filter { it.kind == IrParameterKind.Regular }

                arguments[graphCreatorOwner.parameters.indexOf(regularParams[0])] =
                    builder.irGet(contextParam)

                // factory = createGraphFactory<FeatureGraph.Factory>()
                arguments[graphCreatorOwner.parameters.indexOf(regularParams[1])] =
                    builder.irCall(createGraphFactorySymbol).apply {
                        typeArguments[0] = factoryClass.symbol.typeWith()
                    }

                // extraDependencies
                arguments[graphCreatorOwner.parameters.indexOf(regularParams[2])] = if (hasExtraDeps) {
                    val thisReceiver2 = parentClass.thisReceiver ?: return
                    // Access the constructor param stored as a property
                    val extraDepsProp = parentClass.properties.find { it.name == extraDepsConstructorParam.name }
                    if (extraDepsProp != null) {
                        builder.irCall(extraDepsProp.getter!!).apply {
                            dispatchReceiver = builder.irGet(thisReceiver2)
                        }
                    } else {
                        builder.irGet(extraDepsConstructorParam)
                    }
                } else {
                    builder.irGetObject(emptyExtraDepsClass)
                }
            }
        )

        // Generate getter body: return backingField
        getter.body = DeclarationIrBuilder(pluginContext, getter.symbol).irBlockBody {
            +irReturn(irGetField(irGet(getterThisReceiver), backingField))
        }
    }

    /**
     * Generates `return HasServiceProvider.resolveFrom(graph.value)` for Activity.
     * Generates `return HasServiceProvider.resolveFrom(graphCreator.value)` for Page.
     */
    private fun generateResolveBody(declaration: IrSimpleFunction) {
        val parentClass = declaration.parent as? IrClass ?: return
        val thisReceiver = declaration.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Reference HasServiceProvider companion object
        val hasServiceProviderClass = finder.findClass(Ids.hasServiceProvider)?.owner ?: return
        val companionObject = hasServiceProviderClass.companionObject() ?: return

        // Find resolveFrom function on companion
        val resolveFromFunction = companionObject.functions.first { it.name == Ids.resolveFromName }

        // Determine whether this is an Activity (graph property) or Page (graphCreator property)
        val graphProperty = parentClass.properties.find { it.name == Ids.graphPropertyName }
        val graphCreatorProperty = parentClass.properties.find { it.name == Ids.graphCreatorPropertyName }

        val graphBackingField = (graphProperty ?: graphCreatorProperty)?.backingField ?: return

        // Get the appropriate .value getter
        val valueGetter = if (graphProperty != null) {
            // Activity case: Lazy.value
            val lazyClassId = ClassId(FqName("kotlin"), "Lazy".asName())
            val lazyClass = finder.findClass(lazyClassId) ?: return
            lazyClass.owner.properties.first { it.name.asString() == "value" }.getter!!
        } else {
            // Page case: PageGraphCreator.value
            val pageGraphCreatorClass = finder.findClass(Ids.pageGraphCreator) ?: return
            pageGraphCreatorClass.owner.properties.first { it.name.asString() == "value" }.getter!!
        }

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            // Get backing field, then call .value
            val getGraphField = irGetField(irGet(thisReceiver), graphBackingField)
            val getGraphValue = irCall(valueGetter).apply {
                dispatchReceiver = getGraphField
            }

            // HasServiceProvider.resolveFrom(graphValue)
            val resolveFromCall = irCall(resolveFromFunction).apply {
                dispatchReceiver = irGetObject(companionObject.symbol)
                // type argument T
                typeArguments[0] = declaration.returnType
                // argument: graph.value or graphCreator.value
                arguments[resolveFromFunction.parameters.indexOfFirst { it.kind == IrParameterKind.Regular }] =
                    getGraphValue
            }

            +irReturn(resolveFromCall)
        }
    }

    /**
     * Generates either:
     * - `return feature.params` (for CommonActivity)
     * - `return pageGraphDependencies.initialParam as ParamType` (for ParamPage)
     */
    private fun generateProvideParamBody(declaration: IrSimpleFunction) {
        val regularParams = declaration.parameters.filter { it.kind == IrParameterKind.Regular }
        val firstParam = regularParams.first()
        val firstParamClass = firstParam.type.classOrNull?.owner ?: return

        // Check if the parameter is PageGraphDependencies (ParamPage case)
        val initialParamProperty = firstParamClass.declarations
            .filterIsInstance<IrProperty>()
            .find { it.name == Ids.initialParamName }
        if (initialParamProperty != null) {
            val initialParamGetter = initialParamProperty.getter!!.symbol
            // ParamPage case: return pageGraphDependencies.initialParam as ParamType
            val returnType = declaration.returnType
            declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
                val getInitialParam = irCall(initialParamGetter).apply {
                    dispatchReceiver = irGet(firstParam)
                }
                +irReturn(
                    IrTypeOperatorCallImpl(
                        startOffset, endOffset,
                        returnType,
                        IrTypeOperator.CAST,
                        returnType,
                        getInitialParam
                    )
                )
            }
        } else {
            // CommonActivity case: return feature.params
            val paramsGetterSymbol = firstParamClass.getPropertyGetter("params") ?: return
            declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
                +irReturn(
                    irCall(paramsGetterSymbol).apply {
                        dispatchReceiver = irGet(firstParam)
                    }
                )
            }
        }
    }

    /**
     * Generates: `return provider.createParamFlow(feature, initialParam)`
     */
    private fun generateProvideParamFlowBody(declaration: IrSimpleFunction) {
        val regularParams = declaration.parameters.filter { it.kind == IrParameterKind.Regular }
        val providerParam = regularParams[0]
        val featureParam = regularParams[1]
        val initialParamParam = regularParams[2]

        val providerClass = providerParam.type.classOrNull?.owner ?: return
        val createParamFlowFunction = providerClass.functions.firstOrNull { it.name.asString() == "createParamFlow" }
            ?: return

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(
                irCall(createParamFlowFunction).apply {
                    // arguments[0] = dispatch receiver
                    arguments[0] = irGet(providerParam)
                    // arguments[1] = page (first value param)
                    arguments[1] = irGet(featureParam)
                    // arguments[2] = initialParam (second value param)
                    arguments[2] = irGet(initialParamParam)
                }
            )
        }
    }

    /**
     * Generates: `return feature`
     */
    private fun generateProvideBaseTypeBody(declaration: IrSimpleFunction) {
        val featureParameter = declaration.parameters.first { it.kind == IrParameterKind.Regular }

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(irGet(featureParameter))
        }
    }
}
