package com.bandlab.metro.station.configselector

import com.bandlab.metro.station.utils.ClassIds
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionHintExtension
import dev.zacsweers.metro.compiler.api.fir.MetroContributionHintExtension.ContributionHint
import dev.zacsweers.metro.compiler.compat.CompatContext
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol

/**
 * Implements [MetroContributionHintExtension] to generate cross-module contribution hint files
 * for `MultibindingContribution` interfaces generated by [ContributesConfigSelectorFir].
 *
 * These hint files allow Metro's `ContributionHintFirGenerator` to discover contributions from
 * dependency modules during downstream compilation.
 */
public class ContributesConfigSelectorHintExtension(private val session: FirSession) :
    MetroContributionHintExtension {

    private val predicate = ContributesConfigSelectorIds.predicate

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(predicate)
    }

    override fun getContributionHints(): List<ContributionHint> {
        return session.predicateBasedProvider
            .getSymbolsByPredicate(predicate)
            .filterIsInstance<FirRegularClassSymbol>()
            .map { classSymbol ->
                val nestedInterfaceClassId = classSymbol.classId
                    .createNestedClassId(ContributesConfigSelectorIds.nestedContributionName)
                ContributionHint(
                    contributingClassId = nestedInterfaceClassId,
                    scope = ClassIds.appScope
                )
            }
    }

    public class Factory : MetroContributionHintExtension.Factory {
        override fun create(
            session: FirSession,
            options: MetroOptions,
            compatContext: CompatContext,
        ): MetroContributionHintExtension {
            return ContributesConfigSelectorHintExtension(session)
        }
    }
}
