package com.bandlab.metro.station.configselector

import com.bandlab.metro.station.utils.ClassIds
import com.bandlab.metro.station.utils.findMetroContributionSymbol
import com.fueledbycaffeine.autoservice.AutoService
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId

/**
 * Implements [MetroContributionExtension] to tell Metro's `ContributedInterfaceSupertypeGenerator`
 * about contributions from our generated `MultibindingContribution` interfaces.
 *
 * This is necessary because Metro's predicate-based provider only discovers source declarations and
 * declarations generated by generators that registered the `@ContributesTo` predicate. Our
 * `MultibindingContribution` is generated by [ContributesConfigSelectorFir] (which registers a
 * predicate for `@ContributesConfigSelector`), so Metro's in-compilation discovery doesn't see it.
 */
public class ContributesConfigSelectorContributionExtension(private val session: FirSession) :
    MetroContributionExtension {

    private val predicate = ContributesConfigSelectorIds.predicate

    private val annotatedClasses by lazy {
        session.predicateBasedProvider
            .getSymbolsByPredicate(predicate)
            .filterIsInstance<FirRegularClassSymbol>()
            .toList()
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(predicate)
    }

    override fun getContributions(
        scopeClassId: ClassId,
        typeResolverFactory: MetroFirTypeResolver.Factory,
    ): List<MetroContributionExtension.Contribution> {
        // Feature flags are always contributed to AppScope.
        if (scopeClassId != ClassIds.appScope) return emptyList()

        return annotatedClasses.mapNotNull { parentSymbol ->
            val contributionInterfaceClassId =
                parentSymbol.classId.createNestedClassId(ContributesConfigSelectorIds.nestedContributionName)

            val metroContributionSymbol = contributionInterfaceClassId.findMetroContributionSymbol(session)
                ?: return@mapNotNull null

            MetroContributionExtension.Contribution(
                supertype = metroContributionSymbol.defaultType(),
                replaces = emptyList(),
                originClassId = parentSymbol.classId,
            )
        }
    }

    @AutoService
    public class Factory : MetroContributionExtension.Factory {
        override fun create(
            session: FirSession,
            options: MetroOptions,
            compatContext: CompatContext,
        ): MetroContributionExtension {
            return ContributesConfigSelectorContributionExtension(session)
        }
    }
}
