package com.bandlab.metro.station.graph

import com.bandlab.metro.station.utils.asName
import com.bandlab.metro.station.utils.isSubclassOf
import com.bandlab.metro.station.utils.toCallableId
import org.jetbrains.kotlin.backend.common.extensions.DeclarationFinder
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.builders.*
import org.jetbrains.kotlin.ir.builders.declarations.buildFun
import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.expressions.*
import org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrFunctionExpressionImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl
import org.jetbrains.kotlin.ir.types.classOrNull
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import com.bandlab.metro.station.graph.MetroStationIds as Ids
import com.bandlab.metro.station.utils.ClassIds as MetroClassIds

/**
 * Ir extension that generates code for the dependency graph generated by [MetroStationFir].
 *
 * Note: This class is largely AI-generated, please make sure you have a clear kdoc for each declaration.
 */
public class MetroStationIr : IrGenerationExtension {

    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(MetroStationIrTransformer(pluginContext))
    }
}

private class MetroStationIrTransformer(private val pluginContext: IrPluginContext) :
    IrElementTransformerVoid() {

    private val finder: DeclarationFinder = pluginContext.finderForBuiltins()

    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != MetroStationFir.Key
        ) {
            return super.visitSimpleFunction(declaration)
        }
        if (declaration.body != null) return super.visitSimpleFunction(declaration)
        when (declaration.name) {
            Ids.provideParamName -> generateProvideParamBody(declaration)
            Ids.provideBaseTypeName -> generateProvideBaseTypeBody(declaration)
            Ids.provideParamFlowName -> generateProvideParamFlowBody(declaration)
            Ids.resolveName -> generateResolveBody(declaration)
        }
        return super.visitSimpleFunction(declaration)
    }

    override fun visitClass(declaration: IrClass): IrStatement {
        // Process all children first (fills in graph property bodies, provideParam, etc.)
        super.visitClass(declaration)

        // Check if this class is annotated with @MetroStation
        val hasMetroStation = declaration.annotations.any { annotation ->
            annotation.type.classOrNull?.owner?.classId == Ids.metroStation
        }
        if (!hasMetroStation) return declaration

        // Determine the component type and inject accordingly
        when {
            //TODO: Can we use the impl from the kotlin compiler?
            declaration.isSubclassOf(Ids.androidService) -> injectService(declaration)
            declaration.isSubclassOf(Ids.coroutineWorker) -> injectWorker(declaration)
            declaration.isSubclassOf(Ids.broadcastReceiver) -> injectBroadcastReceiver(declaration)
        }

        return declaration
    }

    /**
     * Injects into a Service class by finding or creating `onCreate()` and prepending
     * the graph creation + member injection call.
     */
    private fun injectService(irClass: IrClass) {
        val onCreateFunction = irClass.functions.find {
            it.name == Ids.onCreateName && it.overriddenSymbols.isNotEmpty()
        }

        if (onCreateFunction != null) {
            // Prepend injection to existing onCreate
            prependInjectionToFunction(irClass, onCreateFunction) { builder, thisReceiver ->
                generateApplicationContextExpr(builder, thisReceiver)
            }
        } else {
            // Generate onCreate with super call + injection
            generateOnCreateWithInjection(irClass)
        }
    }

    /**
     * Injects into a CoroutineWorker class by finding `doWork()` and prepending
     * the graph creation + member injection call.
     */
    private fun injectWorker(irClass: IrClass) {
        val doWorkFunction = irClass.functions.find {
            it.name == Ids.doWorkName && it.overriddenSymbols.isNotEmpty()
        } ?: return

        prependInjectionToFunction(irClass, doWorkFunction) { builder, thisReceiver ->
            generateWorkerApplicationContextExpr(builder, thisReceiver)
        }
    }

    /**
     * Injects into a BroadcastReceiver class by finding `onReceive()` and prepending
     * the graph creation + member injection call using the `context` parameter.
     */
    private fun injectBroadcastReceiver(irClass: IrClass) {
        val onReceiveFunction = irClass.functions.find {
            it.name == Ids.onReceiveName && it.overriddenSymbols.isNotEmpty()
        } ?: return

        prependInjectionToFunction(irClass, onReceiveFunction) { builder, _ ->
            // Use the "context" parameter from onReceive(context: Context, intent: Intent?)
            val contextParam = onReceiveFunction.parameters.first { it.kind == IrParameterKind.Regular }
            builder.irGet(contextParam)
        }
    }

    /**
     * Generates the injection statement:
     * ```
     * createGraphFactory<FeatureGraph.Factory>()
     *   .create(this, contextExpr.resolveServiceProvider(), EmptyExtraDependencies)
     *   .injector
     *   .injectMembers(this)
     * ```
     * and prepends it to the beginning of [function]'s body.
     */
    private fun prependInjectionToFunction(
        irClass: IrClass,
        function: IrSimpleFunction,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ) {
        val existingBody = function.body as? IrBlockBody ?: return
        val thisReceiver = function.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        val builder = DeclarationIrBuilder(pluginContext, function.symbol)
        val injectionStatement = generateInjectionCall(builder, irClass, thisReceiver, contextExprProvider)
            ?: return

        // Prepend the injection statement before existing body statements
        existingBody.statements.add(0, injectionStatement)
    }

    /**
     * Generates a new `onCreate()` override for a Service class that calls `super.onCreate()`
     * followed by the injection code.
     */
    private fun generateOnCreateWithInjection(irClass: IrClass) {
        // Find super's onCreate to override
        val superOnCreate = findSuperFunction(irClass, Ids.onCreateName) ?: return

        val onCreateFunction = pluginContext.irFactory.buildFun {
            name = Ids.onCreateName
            returnType = pluginContext.irBuiltIns.unitType
            visibility = org.jetbrains.kotlin.descriptors.DescriptorVisibilities.PUBLIC
            modality = org.jetbrains.kotlin.descriptors.Modality.OPEN
            origin = IrDeclarationOrigin.GeneratedByPlugin(MetroStationFir.Key)
        }.apply {
            parent = irClass
            overriddenSymbols = listOf(superOnCreate.symbol)
            // Add dispatch receiver parameter (this)
            val thisParam = irClass.thisReceiver!!.copyTo(this, kind = IrParameterKind.DispatchReceiver)
            parameters = listOf(thisParam)
        }

        val builder = DeclarationIrBuilder(pluginContext, onCreateFunction.symbol)
        val thisReceiver = onCreateFunction.parameters.first { it.kind == IrParameterKind.DispatchReceiver }

        onCreateFunction.body = builder.irBlockBody {
            // super.onCreate()
            val superClass = superOnCreate.parent as IrClass
            +IrCallImpl(
                startOffset = UNDEFINED_OFFSET,
                endOffset = UNDEFINED_OFFSET,
                type = pluginContext.irBuiltIns.unitType,
                symbol = superOnCreate.symbol,
                typeArgumentsCount = 0,
                origin = null,
                superQualifierSymbol = superClass.symbol,
            ).apply {
                dispatchReceiver = irGet(thisReceiver)
            }

            // createGraphFactory<...>().create(...).injector.injectMembers(this)
            val injectionCall = generateInjectionCall(builder, irClass, thisReceiver) { b, recv ->
                generateApplicationContextExpr(b, recv)
            }
            if (injectionCall != null) +injectionCall
        }

        irClass.declarations.add(onCreateFunction)
    }

    /**
     * Generates: `createGraphFactory<FeatureGraph.Factory>().create(this, context.resolveServiceProvider<T>(), EmptyExtraDependencies)`
     *
     * @param irClass the class containing the FeatureGraph and FeatureServiceProvider nested classes
     * @param contextExprProvider provides the context expression used as the receiver for `resolveServiceProvider()`
     */
    private fun generateCreateGraphCall(
        builder: IrBuilderWithScope,
        irClass: IrClass,
        thisReceiver: IrValueParameter,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ): IrExpression? {
        // Find FeatureGraph.Factory
        val featureGraphClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return null
        val factoryClass = featureGraphClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return null

        // Reference createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactoryCallableId = MetroClassIds.createGraphFactory.toCallableId()
        val createGraphFactorySymbol = finder.findFunctions(createGraphFactoryCallableId).firstOrNull() ?: return null

        // Reference resolveServiceProvider()
        val resolveServiceProviderCallableId = Ids.resolveServiceProvider.toCallableId()
        val resolveServiceProviderSymbol = finder.findFunctions(resolveServiceProviderCallableId).firstOrNull()
            ?: return null

        // Reference EmptyExtraDependencies
        val emptyExtraDepsClass = finder.findClass(Ids.emptyExtraDependencies) ?: return null

        // Find FeatureServiceProvider type
        val featureServiceProviderClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.featureServiceProviderName }
        val serviceProviderType = featureServiceProviderClass?.symbol?.typeWith()

        // createGraphFactory<FeatureGraph.Factory>()
        val createFactoryCall = builder.irCall(createGraphFactorySymbol).apply {
            typeArguments[0] = factoryClass.symbol.typeWith()
        }

        // Find GraphFactory.create function
        val factoryClassOwner = factoryClass.superTypes
            .mapNotNull { it.classOrNull?.owner }
            .find { it.functions.any { f -> f.name == Ids.createName } }
            ?: factoryClass
        val createFunction = factoryClassOwner.functions.first { it.name == Ids.createName }

        // .create(this, context.resolveServiceProvider(), EmptyExtraDependencies)
        return builder.irCall(createFunction).apply {
            dispatchReceiver = createFactoryCall
            // feature = this
            arguments[1] = builder.irGet(thisReceiver)
            // serviceProvider = context.resolveServiceProvider()
            arguments[2] = builder.irCall(resolveServiceProviderSymbol).apply {
                if (serviceProviderType != null) {
                    typeArguments[0] = serviceProviderType
                }
                // extension receiver = context expression
                arguments[0] = contextExprProvider(builder, thisReceiver)
            }
            // extraDependencies = EmptyExtraDependencies
            arguments[3] = builder.irGetObject(emptyExtraDepsClass)
        }
    }

    private fun generateInjectionCall(
        builder: IrBuilderWithScope,
        irClass: IrClass,
        thisReceiver: IrValueParameter,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ): IrStatement? {
        val createCall = generateCreateGraphCall(builder, irClass, thisReceiver, contextExprProvider) ?: return null

        // .injector
        val membersInjectorProviderClass = finder.findClass(Ids.membersInjectorProvider)?.owner ?: return null
        val injectorGetter = membersInjectorProviderClass.properties
            .first { it.name == Ids.injectorName }.getter ?: return null
        val getInjector = builder.irCall(injectorGetter).apply {
            dispatchReceiver = createCall
        }

        // .injectMembers(this)
        val membersInjectorClass = finder.findClass(Ids.membersInjector)?.owner ?: return null
        val injectMembersFunction = membersInjectorClass.functions
            .first { it.name == Ids.injectMembersName }
        return builder.irCall(injectMembersFunction).apply {
            dispatchReceiver = getInjector
            val regularParamIndex = injectMembersFunction.parameters
                .indexOfFirst { it.kind == IrParameterKind.Regular }
            arguments[regularParamIndex] = builder.irGet(thisReceiver)
        }
    }

    /**
     * Generates `this.getApplicationContext()` for Service (via ContextWrapper).
     */
    private fun generateApplicationContextExpr(
        builder: IrBuilderWithScope,
        thisReceiver: IrValueParameter,
    ): IrExpression {
        val contextWrapperClassId = ClassId(FqName("android.content"), "ContextWrapper".asName())
        val contextWrapperClass = finder.findClass(contextWrapperClassId)?.owner
            ?: error("Cannot find android.content.ContextWrapper class")
        val applicationContextGetter = contextWrapperClass.getSimpleFunction("getApplicationContext")
            ?: error("Cannot find getApplicationContext on ContextWrapper")
        return builder.irCall(applicationContextGetter).apply {
            dispatchReceiver = builder.irGet(thisReceiver)
        }
    }

    /**
     * Generates `this.getApplicationContext()` for Worker (via CoroutineWorker).
     */
    private fun generateWorkerApplicationContextExpr(
        builder: IrBuilderWithScope,
        thisReceiver: IrValueParameter,
    ): IrExpression {
        val coroutineWorkerClass = finder.findClass(Ids.coroutineWorker)?.owner
            ?: error("Cannot find androidx.work.CoroutineWorker class")
        val applicationContextGetter = coroutineWorkerClass.getSimpleFunction("getApplicationContext")
            ?: error("Cannot find getApplicationContext on CoroutineWorker")
        return builder.irCall(applicationContextGetter).apply {
            dispatchReceiver = builder.irGet(thisReceiver)
        }
    }

    /**
     * Finds a function by name in the supertype hierarchy of [irClass].
     */
    private fun findSuperFunction(irClass: IrClass, name: Name): IrSimpleFunction? {
        for (superType in irClass.superTypes) {
            val superClass = superType.classOrNull?.owner ?: continue
            val function = superClass.functions.find { it.name == name }
            if (function != null) return function
            // Check further up the hierarchy
            findSuperFunction(superClass, name)?.let { return it }
        }
        return null
    }

    override fun visitProperty(declaration: IrProperty): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != MetroStationFir.Key
        ) {
            return super.visitProperty(declaration)
        }
        when (declaration.name) {
            Ids.graphPropertyName -> generateGraphPropertyBody(declaration)
            Ids.graphCreatorPropertyName -> generateGraphCreatorPropertyBody(declaration)
        }
        return super.visitProperty(declaration)
    }

    /**
     * Generates the graph property getter body with lazy initialization:
     * ```
     * = lazy {
     *     createGraphFactory<FeatureGraph.Factory>()
     *       .create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies)
     * }
     * ```
     */
    private fun generateGraphPropertyBody(declaration: IrProperty) {
        val getter = declaration.getter ?: return
        val backingField = declaration.backingField ?: return
        val parentClass = declaration.parent as? IrClass ?: return
        val thisReceiver = parentClass.thisReceiver ?: return
        val getterThisReceiver = getter.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Reference kotlin.lazy
        val lazyCallableId = CallableId(FqName("kotlin"), "lazy".asName())
        val lazyFunctions = finder.findFunctions(lazyCallableId)
        // Pick the lazy(LazyThreadSafetyMode, () -> T) or lazy(() -> T) overload
        val lazySymbol =
            lazyFunctions.firstOrNull { it.owner.parameters.count { p -> p.kind == IrParameterKind.Regular } == 1 }
                ?: return

        val graphType = declaration.getter!!.returnType

        // Fix backing field type to Lazy<FeatureGraph> since it stores the lazy delegate
        val lazyClassId = ClassId(FqName("kotlin"), "Lazy".asName())
        val lazyClassSymbol = finder.findClass(lazyClassId) ?: return
        val lazyType = lazyClassSymbol.typeWith(graphType)
        backingField.type = lazyType

        // Build the backing field initializer: lazy { createGraphFactory<Factory>().create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies) }
        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)

        backingField.initializer = pluginContext.irFactory.createExpressionBody(
            builder.irCall(lazySymbol).apply {
                // Set type argument T = graphType
                typeArguments[0] = graphType

                // Build the lambda: { createGraphFactory<Factory>().create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies) }
                val lambdaReturnType = graphType
                val lambdaType = pluginContext.irBuiltIns.functionN(0).typeWith(lambdaReturnType)

                val lambdaFunction = pluginContext.irFactory.buildFun {
                    name = org.jetbrains.kotlin.name.Name.special("<anonymous>")
                    returnType = lambdaReturnType
                    visibility = org.jetbrains.kotlin.descriptors.DescriptorVisibilities.LOCAL
                    origin = IrDeclarationOrigin.LOCAL_FUNCTION_FOR_LAMBDA
                }.apply {
                    parent = backingField

                    body = DeclarationIrBuilder(pluginContext, symbol).irBlockBody {
                        val createCall = generateCreateGraphCall(
                            this, parentClass, thisReceiver, ::generateApplicationContextExpr
                        ) ?: return@irBlockBody
                        +irReturn(createCall)
                    }
                }

                val lambdaExpression = IrFunctionExpressionImpl(
                    startOffset = UNDEFINED_OFFSET,
                    endOffset = UNDEFINED_OFFSET,
                    type = lambdaType,
                    function = lambdaFunction,
                    origin = IrStatementOrigin.LAMBDA,
                )

                // arguments[0] = lambda (the regular parameter)
                arguments[lazySymbol.owner.parameters.indexOfFirst { it.kind == IrParameterKind.Regular }] =
                    lambdaExpression
            }
        )

        // Reference Lazy.value getter
        val lazyClass = finder.findClass(lazyClassId) ?: return
        val lazyValueGetter = lazyClass.owner.properties.first { it.name.asString() == "value" }.getter!!

        // Generate getter body: return backingField.value
        getter.body = DeclarationIrBuilder(pluginContext, getter.symbol).irBlockBody {
            val getLazy = irGetField(irGet(getterThisReceiver), backingField)
            val getValue = irCall(lazyValueGetter).apply {
                dispatchReceiver = getLazy
            }
            +irReturn(getValue)
        }
    }

    /**
     * Generates the graph property getter body with lazy initialization:
     * ```
     * = lazy {
     *     graphCreator(
     *         context, // Context, or ComponentActivity
     *         createGraphFactory<OpenRevisionDialogGraph.Factory>(),
     *         EmptyExtraDependencies // Or actual extra dependencies if it's presented in the annotation
     *     )
     * }
     * ```
     */
    private fun generateGraphCreatorPropertyBody(declaration: IrProperty) {
        val getter = declaration.getter ?: return
        val backingField = declaration.backingField ?: return
        val parentClass = declaration.parent as? IrClass ?: return
        val getterThisReceiver = getter.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Find FeatureGraph.Factory nested class
        val featureGraphClass = parentClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return
        val factoryClass = featureGraphClass.declarations
            .filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return

        // Find context parameter from the class constructor
        val contextClass = finder.findClass(Ids.context)
        val componentActivityClass = finder.findClass(Ids.componentActivity)

        val primaryConstructor = parentClass.declarations
            .filterIsInstance<IrConstructor>()
            .firstOrNull { it.isPrimary }
            ?: error("Cannot find primary constructor for ${parentClass.name}")

        val contextParam = primaryConstructor.parameters
            .filter { it.kind == IrParameterKind.Regular }
            .find { param ->
                val paramClassSymbol = param.type.classOrNull
                paramClassSymbol == contextClass || paramClassSymbol == componentActivityClass
            } ?: error("Cannot find Context or ComponentActivity parameter in constructor of ${parentClass.name}")

        // Reference createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactoryCallableId = MetroClassIds.createGraphFactory.toCallableId()
        val createGraphFactoryFunctions = finder.findFunctions(createGraphFactoryCallableId)
        val createGraphFactorySymbol = createGraphFactoryFunctions.firstOrNull() ?: return

        // Reference graphCreator extension function
        val graphCreatorCallableId = Ids.pageGraphCreatorExtension.toCallableId()
        val graphCreatorFunctions = finder.findFunctions(graphCreatorCallableId)
        val graphCreatorSymbol = graphCreatorFunctions.firstOrNull() ?: return

        // Determine extraDependencies: check annotation for extraDependencies parameter
        // If present, find matching constructor parameter; otherwise use EmptyExtraDependencies
        val emptyExtraDepsClass = finder.findClass(Ids.emptyExtraDependencies) ?: return

        // Read the @MetroStation annotation from the parent class
        val metroStationAnnotation = parentClass.annotations.find { annotation ->
            annotation.type.classOrNull?.owner?.name == Ids.metroStation.shortClassName
        }

        // Check if extraDependencies is specified (not null/Nothing)
        val extraDepsClassRef = metroStationAnnotation?.let { annotation ->
            // Find the extraDependencies parameter index in the full parameters list
            val extraDepsParamIndex = annotation.symbol.owner.parameters
                .indexOfFirst { it.kind == IrParameterKind.Regular && it.name == Ids.extraDependenciesName }
                .takeIf { it >= 0 }
            extraDepsParamIndex?.let { idx ->
                val arg = annotation.arguments[idx] ?: return@let null
                // Filter out Nothing::class (means no extra dependencies specified)
                val classRef = arg as? IrClassReference
                if (classRef != null && classRef.classType == pluginContext.irBuiltIns.nothingType) {
                    null
                } else {
                    arg
                }
            }
        }

        // Determine if we have a non-trivial extraDependencies type (non-null means it was specified)
        val extraDepsRefType = (extraDepsClassRef as? IrClassReference)?.classType
        val extraDepsConstructorParam = if (extraDepsRefType != null) {
            primaryConstructor.parameters
                .filter { it.kind == IrParameterKind.Regular }
                .find { param -> param.type.classOrNull == extraDepsRefType.classOrNull }
        } else null
        val hasExtraDeps = extraDepsConstructorParam != null

        // Find the extra dependencies expression to pass
        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)

        backingField.initializer = pluginContext.irFactory.createExpressionBody(
            builder.irCall(graphCreatorSymbol).apply {
                val graphCreatorOwner = graphCreatorSymbol.owner
                val thisReceiver = parentClass.thisReceiver ?: return

                // Extension receiver = this (the Page)
                val extensionReceiverIndex = graphCreatorOwner.parameters.indexOfFirst { it.kind == IrParameterKind.ExtensionReceiver }
                if (extensionReceiverIndex >= 0) {
                    arguments[extensionReceiverIndex] = builder.irGet(thisReceiver)
                }

                // Type arguments: Root, ServiceProvider, ExtraDependencies, Graph
                val featureServiceProviderClass = parentClass.declarations
                    .filterIsInstance<IrClass>()
                    .find { it.name == Ids.featureServiceProviderName }
                val serviceProviderType = featureServiceProviderClass?.symbol?.typeWith()

                val graphType = featureGraphClass.symbol.typeWith()

                typeArguments[0] = parentClass.symbol.typeWith() // Root
                if (serviceProviderType != null) typeArguments[1] = serviceProviderType // ServiceProvider

                // Determine extraDependencies type
                val extraDepsType = if (hasExtraDeps) {
                    extraDepsConstructorParam.type
                } else {
                    emptyExtraDepsClass.typeWith()
                }
                typeArguments[2] = extraDepsType // ExtraDependencies
                typeArguments[3] = graphType // Graph

                // Regular parameters: context, factory, extraDependencies
                val regularParams = graphCreatorOwner.parameters.filter { it.kind == IrParameterKind.Regular }

                arguments[graphCreatorOwner.parameters.indexOf(regularParams[0])] =
                    builder.irGet(contextParam)

                // factory = createGraphFactory<FeatureGraph.Factory>()
                arguments[graphCreatorOwner.parameters.indexOf(regularParams[1])] =
                    builder.irCall(createGraphFactorySymbol).apply {
                        typeArguments[0] = factoryClass.symbol.typeWith()
                    }

                // extraDependencies
                arguments[graphCreatorOwner.parameters.indexOf(regularParams[2])] = if (hasExtraDeps) {
                    val thisReceiver2 = parentClass.thisReceiver ?: return
                    // Access the constructor param stored as a property
                    val extraDepsProp = parentClass.properties.find { it.name == extraDepsConstructorParam.name }
                    if (extraDepsProp != null) {
                        builder.irCall(extraDepsProp.getter!!).apply {
                            dispatchReceiver = builder.irGet(thisReceiver2)
                        }
                    } else {
                        builder.irGet(extraDepsConstructorParam)
                    }
                } else {
                    builder.irGetObject(emptyExtraDepsClass)
                }
            }
        )

        // Generate getter body: return backingField
        getter.body = DeclarationIrBuilder(pluginContext, getter.symbol).irBlockBody {
            +irReturn(irGetField(irGet(getterThisReceiver), backingField))
        }
    }

    /**
     * Generates `return HasServiceProvider.resolveFrom(graph.value)` for Activity.
     * Generates `return HasServiceProvider.resolveFrom(graphCreator.value)` for Page.
     */
    private fun generateResolveBody(declaration: IrSimpleFunction) {
        val parentClass = declaration.parent as? IrClass ?: return
        val thisReceiver = declaration.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // Reference HasServiceProvider companion object
        val hasServiceProviderClass = finder.findClass(Ids.hasServiceProvider)?.owner ?: return
        val companionObject = hasServiceProviderClass.companionObject() ?: return

        // Find resolveFrom function on companion
        val resolveFromFunction = companionObject.functions.first { it.name == Ids.resolveFromName }

        // Determine whether this is an Activity (graph property) or Page (graphCreator property)
        val graphProperty = parentClass.properties.find { it.name == Ids.graphPropertyName }
        val graphCreatorProperty = parentClass.properties.find { it.name == Ids.graphCreatorPropertyName }

        val graphBackingField = (graphProperty ?: graphCreatorProperty)?.backingField ?: return

        // Get the appropriate .value getter
        val valueGetter = if (graphProperty != null) {
            // Activity case: Lazy.value
            val lazyClassId = ClassId(FqName("kotlin"), "Lazy".asName())
            val lazyClass = finder.findClass(lazyClassId) ?: return
            lazyClass.owner.properties.first { it.name.asString() == "value" }.getter!!
        } else {
            // Page case: PageGraphCreator.value
            val pageGraphCreatorClass = finder.findClass(Ids.pageGraphCreator) ?: return
            pageGraphCreatorClass.owner.properties.first { it.name.asString() == "value" }.getter!!
        }

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            // Get backing field, then call .value
            val getGraphField = irGetField(irGet(thisReceiver), graphBackingField)
            val getGraphValue = irCall(valueGetter).apply {
                dispatchReceiver = getGraphField
            }

            // HasServiceProvider.resolveFrom(graphValue)
            val resolveFromCall = irCall(resolveFromFunction).apply {
                dispatchReceiver = irGetObject(companionObject.symbol)
                // type argument T
                typeArguments[0] = declaration.returnType
                // argument: graph.value or graphCreator.value
                arguments[resolveFromFunction.parameters.indexOfFirst { it.kind == IrParameterKind.Regular }] =
                    getGraphValue
            }

            +irReturn(resolveFromCall)
        }
    }

    /**
     * Generates either:
     * - `return feature.params` (for CommonActivity)
     * - `return pageGraphDependencies.initialParam as ParamType` (for ParamPage)
     */
    private fun generateProvideParamBody(declaration: IrSimpleFunction) {
        val regularParams = declaration.parameters.filter { it.kind == IrParameterKind.Regular }
        val firstParam = regularParams.first()
        val firstParamClass = firstParam.type.classOrNull?.owner ?: return

        // Check if the parameter is PageGraphDependencies (ParamPage case)
        val initialParamProperty = firstParamClass.declarations
            .filterIsInstance<IrProperty>()
            .find { it.name == Ids.initialParamName }
        if (initialParamProperty != null) {
            val initialParamGetter = initialParamProperty.getter!!.symbol
            // ParamPage case: return pageGraphDependencies.initialParam as ParamType
            val returnType = declaration.returnType
            declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
                val getInitialParam = irCall(initialParamGetter).apply {
                    dispatchReceiver = irGet(firstParam)
                }
                +irReturn(
                    IrTypeOperatorCallImpl(
                        startOffset, endOffset,
                        returnType,
                        IrTypeOperator.CAST,
                        returnType,
                        getInitialParam
                    )
                )
            }
        } else {
            // CommonActivity case: return feature.params
            val paramsGetterSymbol = firstParamClass.getPropertyGetter("params") ?: return
            declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
                +irReturn(
                    irCall(paramsGetterSymbol).apply {
                        dispatchReceiver = irGet(firstParam)
                    }
                )
            }
        }
    }

    /**
     * Generates: `return provider.createParamFlow(feature, initialParam)`
     */
    private fun generateProvideParamFlowBody(declaration: IrSimpleFunction) {
        val regularParams = declaration.parameters.filter { it.kind == IrParameterKind.Regular }
        val providerParam = regularParams[0]
        val featureParam = regularParams[1]
        val initialParamParam = regularParams[2]

        val providerClass = providerParam.type.classOrNull?.owner ?: return
        val createParamFlowFunction = providerClass.functions.firstOrNull { it.name.asString() == "createParamFlow" }
            ?: return

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(
                irCall(createParamFlowFunction).apply {
                    // arguments[0] = dispatch receiver
                    arguments[0] = irGet(providerParam)
                    // arguments[1] = page (first value param)
                    arguments[1] = irGet(featureParam)
                    // arguments[2] = initialParam (second value param)
                    arguments[2] = irGet(initialParamParam)
                }
            )
        }
    }

    /**
     * Generates: `return feature`
     */
    private fun generateProvideBaseTypeBody(declaration: IrSimpleFunction) {
        val featureParameter = declaration.parameters.first { it.kind == IrParameterKind.Regular }

        declaration.body = DeclarationIrBuilder(pluginContext, declaration.symbol).irBlockBody {
            +irReturn(irGet(featureParameter))
        }
    }
}
