package com.bandlab.metro.station.graph

import com.bandlab.metro.station.utils.*
import org.jetbrains.kotlin.backend.common.extensions.DeclarationFinder
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.builders.*
import org.jetbrains.kotlin.ir.builders.declarations.buildField
import org.jetbrains.kotlin.ir.builders.declarations.buildFun
import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl
import org.jetbrains.kotlin.ir.types.*
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import com.bandlab.metro.station.graph.MetroStationIds as Ids
import com.bandlab.metro.station.utils.ClassIds as MetroClassIds

/**
 * IR extension that fills in code for the graph extension FIR structures generated by [MetroStationFir].
 */
public class MetroStationIr : IrGenerationExtension {

    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(MetroStationIrTransformer(pluginContext))
    }
}

private class MetroStationIrTransformer(private val pluginContext: IrPluginContext) :
    IrElementTransformerVoid() {

    private val finder: DeclarationFinder = pluginContext.finderForBuiltins()

    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        val origin = declaration.origin
        if (
            origin !is IrDeclarationOrigin.GeneratedByPlugin ||
            origin.pluginKey != MetroStationFir.Key
        ) {
            return super.visitSimpleFunction(declaration)
        }
        if (declaration.body != null) return super.visitSimpleFunction(declaration)
        when (declaration.name) {
            Ids.provideParamName -> generateProvideParamBody(pluginContext, declaration)
            Ids.provideBaseTypeName -> generateProvideBaseTypeBody(pluginContext, declaration)
            Ids.provideParamFlowName -> generateProvideParamFlowBody(pluginContext, declaration)
            Ids.injectName -> generateInjectBody(declaration)
            Ids.injectViewModelName -> generateInjectViewModelBody(declaration)
        }
        return super.visitSimpleFunction(declaration)
    }

    override fun visitClass(declaration: IrClass): IrStatement {
        // Synthesize a backing field for extraDependencies if the parameter is not declared as `val`.
        // This must happen before processing children, since generateInjectViewModelBody needs the field.
        synthesizeExtraDependenciesFieldIfNeeded(declaration)

        // Process all children first (fills in graph property bodies, provideParam, etc.)
        super.visitClass(declaration)

        // Check if this class is annotated with @MetroStation
        val hasMetroStation = declaration.annotations.any { annotation ->
            annotation.type.classOrNull?.owner?.classId == Ids.metroStation
        }
        if (!hasMetroStation) return declaration

        fun isSubclassOf(classId: ClassId): Boolean {
            return finder.findClass(classId)?.owner?.let { declaration.isSubclassOf(it) } == true
        }

        // Determine the component type and inject accordingly
        when {
            isSubclassOf(Ids.androidService) -> injectService(declaration)
            isSubclassOf(Ids.coroutineWorker) -> injectWorker(declaration)
            isSubclassOf(Ids.broadcastReceiver) -> injectBroadcastReceiver(declaration)
        }

        return declaration
    }

    /**
     * Injects into a Service class by finding or creating `onCreate()` and prepending
     * the graph creation + member injection call.
     */
    private fun injectService(irClass: IrClass) {
        val onCreateFunction = irClass.functions.find {
            it.name == Ids.onCreateName && it.overriddenSymbols.isNotEmpty() && !it.isFakeOverride
        }

        if (onCreateFunction != null) {
            // Prepend injection to existing onCreate
            prependInjectionToFunction(irClass, onCreateFunction) { builder, thisReceiver ->
                generateApplicationContextExpr(builder, thisReceiver)
            }
        } else {
            // Generate onCreate with super call + injection
            generateOnCreateWithInjection(irClass)
        }
    }

    /**
     * Injects into a CoroutineWorker class by finding `doWork()` and prepending
     * the graph creation + member injection call.
     */
    private fun injectWorker(irClass: IrClass) {
        val doWorkFunction = irClass.functions.find {
            it.name == Ids.doWorkName && it.overriddenSymbols.isNotEmpty()
        } ?: return

        prependInjectionToFunction(irClass, doWorkFunction) { builder, thisReceiver ->
            generateApplicationContextExpr(builder, thisReceiver, Ids.coroutineWorker)
        }
    }

    /**
     * Injects into a BroadcastReceiver class by finding `onReceive()` and prepending
     * the graph creation + member injection call using the `context` parameter.
     */
    private fun injectBroadcastReceiver(irClass: IrClass) {
        val onReceiveFunction = irClass.functions.find {
            it.name == Ids.onReceiveName && it.overriddenSymbols.isNotEmpty()
        } ?: return

        prependInjectionToFunction(irClass, onReceiveFunction) { builder, _ ->
            // Use the "context" parameter from onReceive(context: Context, intent: Intent?)
            val contextParam = onReceiveFunction.parameters.first { it.kind == IrParameterKind.Regular }
            builder.irGet(contextParam)
        }
    }

    /**
     * Generates the injection statement:
     * ```
     * createGraphFactory<FeatureGraph.Factory>()
     *   .create(this, contextExpr.resolveServiceProvider(), EmptyExtraDependencies)
     *   .injector
     *   .injectMembers(this)
     * ```
     * and prepends it to the beginning of [function]'s body.
     */
    private fun prependInjectionToFunction(
        irClass: IrClass,
        function: IrSimpleFunction,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ) {
        val existingBody = function.body as? IrBlockBody ?: return
        val thisReceiver = function.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        val builder = DeclarationIrBuilder(pluginContext, function.symbol)
        val injectionStatement = generateInjectionCall(builder, irClass, thisReceiver, contextExprProvider)
            ?: return

        // Prepend the injection statement before existing body statements
        existingBody.statements.add(0, injectionStatement)
    }

    /**
     * Generates a new `onCreate()` override for a Service class that calls `super.onCreate()`
     * followed by the injection code.
     */
    private fun generateOnCreateWithInjection(irClass: IrClass) {
        // Find super's onCreate to override
        val superOnCreate = findSuperFunction(irClass, Ids.onCreateName) ?: return

        val onCreateFunction = pluginContext.irFactory.buildFun {
            name = Ids.onCreateName
            returnType = pluginContext.irBuiltIns.unitType
            visibility = org.jetbrains.kotlin.descriptors.DescriptorVisibilities.PUBLIC
            modality = org.jetbrains.kotlin.descriptors.Modality.OPEN
            origin = IrDeclarationOrigin.GeneratedByPlugin(MetroStationFir.Key)
        }.apply {
            parent = irClass
            overriddenSymbols = listOf(superOnCreate.symbol)
            // Add dispatch receiver parameter (this)
            val thisParam = irClass.thisReceiver!!.copyTo(this, kind = IrParameterKind.DispatchReceiver)
            parameters = listOf(thisParam)
        }

        val builder = DeclarationIrBuilder(pluginContext, onCreateFunction.symbol)
        val thisReceiver = onCreateFunction.parameters.first { it.kind == IrParameterKind.DispatchReceiver }

        onCreateFunction.body = builder.irBlockBody {
            // super.onCreate()
            val superClass = superOnCreate.parent as IrClass
            +IrCallImpl(
                startOffset = UNDEFINED_OFFSET,
                endOffset = UNDEFINED_OFFSET,
                type = pluginContext.irBuiltIns.unitType,
                symbol = superOnCreate.symbol,
                typeArgumentsCount = 0,
                origin = null,
                superQualifierSymbol = superClass.symbol,
            ).apply {
                dispatchReceiver = irGet(thisReceiver)
            }

            // createGraphFactory<...>().create(...).injector.injectMembers(this)
            val injectionCall = generateInjectionCall(builder, irClass, thisReceiver) { b, recv ->
                generateApplicationContextExpr(b, recv)
            }
            if (injectionCall != null) +injectionCall
        }

        // Remove the fake override of onCreate before adding the real implementation
        irClass.declarations.removeAll {
            it is IrSimpleFunction && it.name == Ids.onCreateName && it.isFakeOverride
        }
        irClass.declarations.add(onCreateFunction)
    }

    /**
     * Generates: `createGraphFactory<FeatureGraph.Factory>().create(this, context.resolveServiceProvider<T>(), EmptyExtraDependencies)`
     *
     * @param irClass the class containing the FeatureGraph and FeatureServiceProvider nested classes
     * @param contextExprProvider provides the context expression used as the receiver for `resolveServiceProvider()`
     */
    private fun generateCreateGraphCall(
        builder: IrBuilderWithScope,
        irClass: IrClass,
        thisReceiver: IrValueParameter,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ): IrExpression? {
        // Find FeatureGraph.Factory
        val featureGraphClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return null
        val factoryClass = featureGraphClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return null

        // Reference createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactoryCallableId = MetroClassIds.createGraphFactory.toCallableId()
        val createGraphFactorySymbol = finder.findFunctions(createGraphFactoryCallableId).firstOrNull() ?: return null

        // Reference resolveServiceProvider()
        val resolveServiceProviderCallableId = Ids.resolveServiceProvider.toCallableId()
        val resolveServiceProviderSymbol = finder.findFunctions(resolveServiceProviderCallableId).firstOrNull()
            ?: return null

        // Reference EmptyExtraDependencies
        val emptyExtraDepsClass = finder.findClass(Ids.emptyExtraDependencies) ?: return null

        // Find FeatureServiceProvider type
        val featureServiceProviderClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.featureServiceProviderName }
        val serviceProviderType = featureServiceProviderClass?.symbol?.typeWith()

        // createGraphFactory<FeatureGraph.Factory>()
        val createFactoryCall = builder.irCall(createGraphFactorySymbol).apply {
            typeArguments[0] = factoryClass.symbol.typeWith()
        }

        // Find GraphFactory.create function
        val factoryClassOwner = factoryClass.superTypes
            .mapNotNull { it.classOrNull?.owner }
            .find { it.functions.any { f -> f.name == Ids.createName } }
            ?: factoryClass
        val createFunction = factoryClassOwner.functions.first { it.name == Ids.createName }

        // .create(this, context.resolveServiceProvider(), EmptyExtraDependencies)
        return builder.irCall(createFunction).apply {
            dispatchReceiver = createFactoryCall
            // feature = this
            arguments[1] = builder.irGet(thisReceiver)
            // serviceProvider = context.resolveServiceProvider()
            arguments[2] = builder.irCall(resolveServiceProviderSymbol).apply {
                if (serviceProviderType != null) {
                    typeArguments[0] = serviceProviderType
                }
                // extension receiver = context expression
                arguments[0] = contextExprProvider(builder, thisReceiver)
            }
            // extraDependencies = EmptyExtraDependencies
            arguments[3] = builder.irGetObject(emptyExtraDepsClass)
        }
    }

    private fun generateInjectionCall(
        builder: IrBuilderWithScope,
        irClass: IrClass,
        thisReceiver: IrValueParameter,
        contextExprProvider: (IrBuilderWithScope, IrValueParameter) -> IrExpression,
    ): IrStatement? {
        val createCall = generateCreateGraphCall(builder, irClass, thisReceiver, contextExprProvider) ?: return null

        // .injector
        val membersInjectorProviderClass = finder.findClass(Ids.membersInjectorProvider)?.owner ?: return null
        val injectorGetter = membersInjectorProviderClass.properties
            .first { it.name == Ids.injectorName }.getter ?: return null
        val getInjector = builder.irCall(injectorGetter).apply {
            dispatchReceiver = createCall
        }

        // .injectMembers(this)
        val membersInjectorClass = finder.findClass(Ids.membersInjector)?.owner ?: return null
        val injectMembersFunction = membersInjectorClass.functions
            .first { it.name == Ids.injectMembersName }
        return builder.irCall(injectMembersFunction).apply {
            dispatchReceiver = getInjector
            val regularParamIndex = injectMembersFunction.parameters
                .indexOfFirst { it.kind == IrParameterKind.Regular }
            arguments[regularParamIndex] = builder.irGet(thisReceiver)
        }
    }

    /**
     * Generates the body of the FIR-generated `inject()` override on an annotated activity:
     * ```
     * createGraphFactory<FeatureGraph.Factory>()
     *     .create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies)
     *     .injector
     *     .injectMembers(this)
     * ```
     */
    private fun generateInjectBody(declaration: IrSimpleFunction) {
        val irClass = declaration.parentClassOrNull ?: return
        val thisReceiver = declaration.parameters
            .firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)
        val injectionCall = generateInjectionCall(builder, irClass, thisReceiver) { b, recv ->
            generateApplicationContextExpr(b, recv)
        } ?: return

        declaration.body = builder.irBlockBody {
            +injectionCall
        }
    }

    /**
     * Generates the body of the FIR-generated `injectViewModel(deps[, initialParam])` override on an
     * annotated page:
     * ```
     * return createGraphAndInjectViewModel(
     *     deps,
     *     initialParam | Unit,
     *     createGraphFactory<FeatureGraph.Factory>(),
     *     extraDependencies,
     * )
     * ```
     * The 6 type arguments are read off the `PageGraphFactory<...>` supertype of the generated
     * `FeatureGraph.Factory`, which carries them in the order
     * `[Feature, VM, Param, ServiceProvider, ExtraDependencies, Graph]` — matching the type parameter
     * order of `createGraphAndInjectViewModel`.
     */
    private fun generateInjectViewModelBody(declaration: IrSimpleFunction) {
        val irClass = declaration.parentClassOrNull ?: return
        val thisReceiver = declaration.parameters
            .firstOrNull { it.kind == IrParameterKind.DispatchReceiver } ?: return

        // FeatureGraph.Factory
        val featureGraphClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return
        val factoryClass = featureGraphClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return

        // PageGraphFactory<Feature, VM, Param, ServiceProvider, ExtraDependencies, Graph> supertype
        val pageGraphFactorySuperType = factoryClass.superTypes
            .filterIsInstance<IrSimpleType>()
            .find { it.classOrNull?.owner?.classId == Ids.pageGraphFactory } ?: return
        val factoryTypeArgs = pageGraphFactorySuperType.arguments.mapNotNull { it.typeOrNull }
        if (factoryTypeArgs.size < 6) return
        val extraDependenciesType = factoryTypeArgs[4]

        // createGraphFactory<FeatureGraph.Factory>()
        val createGraphFactorySymbol = finder
            .findFunctions(MetroClassIds.createGraphFactory.toCallableId()).firstOrNull() ?: return
        // createGraphAndInjectViewModel(deps, param, factory, extraDependencies)
        val createGraphAndInjectViewModelSymbol = finder
            .findFunctions(Ids.createGraphAndInjectViewModel.toCallableId()).firstOrNull() ?: return

        val builder = DeclarationIrBuilder(pluginContext, declaration.symbol)

        val createFactoryCall = builder.irCall(createGraphFactorySymbol).apply {
            typeArguments[0] = factoryClass.symbol.typeWith()
        }

        val regularParams = declaration.parameters.filter { it.kind == IrParameterKind.Regular }
        val depsValueParam = regularParams.firstOrNull() ?: return
        val initialParamValueParam = regularParams.getOrNull(1)
        // ParamPage passes its initialParam; a plain Page passes Unit.
        val paramExpr = if (initialParamValueParam != null) {
            builder.irGet(initialParamValueParam)
        } else {
            builder.irGetObject(pluginContext.irBuiltIns.unitClass)
        }

        val extraDepsExpr =
            resolveExtraDependenciesExpr(builder, irClass, thisReceiver, extraDependenciesType) ?: return

        val createGraphAndInjectViewModelFn = createGraphAndInjectViewModelSymbol.owner
        val call = builder.irCall(createGraphAndInjectViewModelSymbol).apply {
            factoryTypeArgs.take(6).forEachIndexed { index, typeArg -> typeArguments[index] = typeArg }
            createGraphAndInjectViewModelFn.parameters.forEachIndexed { index, param ->
                arguments[index] = when {
                    param.kind == IrParameterKind.ExtensionReceiver -> builder.irGet(thisReceiver)
                    param.name == Ids.depsName -> builder.irGet(depsValueParam)
                    param.name == Ids.factoryParamName -> createFactoryCall
                    param.name == Ids.extraDependenciesName -> extraDepsExpr
                    else -> paramExpr
                }
            }
        }

        declaration.body = builder.irBlockBody {
            +irReturn(call)
        }
    }

    /**
     * Resolves the expression passed as `extraDependencies` to `createGraphAndInjectViewModel`:
     * - the `EmptyExtraDependencies` object when [extraDependenciesType] is that empty marker, or
     * - the value of the page property whose type matches [extraDependenciesType] otherwise
     *   (supports both `val` properties and synthesized backing fields).
     */
    private fun resolveExtraDependenciesExpr(
        builder: IrBuilderWithScope,
        irClass: IrClass,
        thisReceiver: IrValueParameter,
        extraDependenciesType: IrType,
    ): IrExpression? {
        val extraDepsClassSymbol = extraDependenciesType.classOrNull
        if (extraDepsClassSymbol?.owner?.classId == Ids.emptyExtraDependencies) {
            val emptyClass = finder.findClass(Ids.emptyExtraDependencies) ?: return null
            return builder.irGetObject(emptyClass)
        }
        // Try finding a `val` property with getter first
        val property = irClass.properties.firstOrNull { prop ->
            prop.backingField?.type?.classOrNull == extraDepsClassSymbol
        }
        if (property != null) {
            val getter = property.getter ?: return null
            return builder.irCall(getter.symbol).apply {
                dispatchReceiver = builder.irGet(thisReceiver)
            }
        }
        // Fall back to reading from the synthesized backing field (non-val parameter)
        val field = irClass.declarations.filterIsInstance<IrField>().firstOrNull { f ->
            f.type.classOrNull == extraDepsClassSymbol
        } ?: return null
        return builder.irGetField(builder.irGet(thisReceiver), field)
    }

    /**
     * For classes with a non-empty `extraDependencies` type where the constructor parameter is NOT
     * declared as `val`, synthesizes a private backing field and initializes it from the constructor
     * parameter. This allows [resolveExtraDependenciesExpr] to read the value later.
     */
    private fun synthesizeExtraDependenciesFieldIfNeeded(irClass: IrClass) {
        // Check if class has @MetroStation
        val hasMetroStation = irClass.annotations.any { annotation ->
            annotation.type.classOrNull?.owner?.classId == Ids.metroStation
        }
        if (!hasMetroStation) return

        // Find FeatureGraph.Factory to get the extra deps type
        val featureGraphClass = irClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.graphName } ?: return
        val factoryClass = featureGraphClass.declarations.filterIsInstance<IrClass>()
            .find { it.name == Ids.nestedFactoryName } ?: return

        // Extract extra dependencies type from the factory's supertype
        val extraDepsType = run {
            val pageFactorySuperType = factoryClass.superTypes
                .filterIsInstance<IrSimpleType>()
                .find { it.classOrNull?.owner?.classId == Ids.pageGraphFactory }
            if (pageFactorySuperType != null) {
                val args = pageFactorySuperType.arguments.mapNotNull { it.typeOrNull }
                if (args.size < 5) return
                args[4]
            } else {
                val graphFactorySuperType = factoryClass.superTypes
                    .filterIsInstance<IrSimpleType>()
                    .find { it.classOrNull?.owner?.classId == Ids.graphFactory } ?: return
                val args = graphFactorySuperType.arguments.mapNotNull { it.typeOrNull }
                if (args.size < 3) return
                args[2]
            }
        }

        val extraDepsClassSymbol = extraDepsType.classOrNull ?: return

        // If it's EmptyExtraDependencies, no field needed
        if (extraDepsClassSymbol.owner.classId == Ids.emptyExtraDependencies) return

        // Check if a property already exists for this type (e.g., user declared `val`)
        val existingProperty = irClass.properties.any { prop ->
            prop.backingField?.type?.classOrNull == extraDepsClassSymbol
        }
        if (existingProperty) return

        // Find the constructor parameter with this type
        val primaryConstructor = irClass.primaryConstructor ?: return
        val extraDepsParam = primaryConstructor.parameters.firstOrNull { param ->
            param.kind == IrParameterKind.Regular && param.type.classOrNull == extraDepsClassSymbol
        } ?: return

        // Create a backing field
        val field = pluginContext.irFactory.buildField {
            name = extraDepsParam.name
            type = extraDepsParam.type
            visibility = org.jetbrains.kotlin.descriptors.DescriptorVisibilities.PRIVATE
            isFinal = true
            origin = IrDeclarationOrigin.GeneratedByPlugin(MetroStationFir.Key)
        }.apply {
            parent = irClass
        }

        // Add field to class declarations
        irClass.declarations.add(field)

        // Add initialization in constructor body: this.<field> = param
        val constructorBody = primaryConstructor.body as? IrBlockBody ?: return
        val builder = DeclarationIrBuilder(pluginContext, primaryConstructor.symbol)
        val thisParam = primaryConstructor.parameters.firstOrNull { it.kind == IrParameterKind.DispatchReceiver }
            ?: irClass.thisReceiver
            ?: return
        val setField = builder.irSetField(builder.irGet(thisParam), field, builder.irGet(extraDepsParam))
        constructorBody.statements.add(setField)
    }

    /**
     * Generates `this.getApplicationContext()` by looking up the method on the given [classId].
     */
    private fun generateApplicationContextExpr(
        builder: IrBuilderWithScope,
        thisReceiver: IrValueParameter,
        classId: ClassId = ClassId(FqName("android.content"), "ContextWrapper".asName()),
    ): IrExpression {
        val ownerClass = finder.findClass(classId)?.owner
            ?: error("Cannot find ${classId.asSingleFqName()} class")
        val applicationContextGetter = ownerClass.getSimpleFunction("getApplicationContext")
            ?: error("Cannot find getApplicationContext on ${classId.shortClassName}")
        return builder.irCall(applicationContextGetter).apply {
            dispatchReceiver = builder.irGet(thisReceiver)
        }
    }

    /**
     * Finds a function by name in the supertype hierarchy of [irClass].
     */
    private fun findSuperFunction(irClass: IrClass, name: Name): IrSimpleFunction? {
        for (superType in irClass.superTypes) {
            val superClass = superType.classOrNull?.owner ?: continue
            val function = superClass.functions.find { it.name == name }
            if (function != null) return function
            // Check further up the hierarchy
            findSuperFunction(superClass, name)?.let { return it }
        }
        return null
    }
}
