

package com.bandlab.metro.station.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.station.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/configselector")
  @TestDataPath("$PROJECT_ROOT")
  public class Configselector {
    @Test
    public void testAllFilesPresentInConfigselector() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/configselector"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      runTest("compiler-plugin/testData/box/configselector/basic.kt");
    }

    @Test
    @TestMetadata("crossModule.kt")
    public void testCrossModule() {
      runTest("compiler-plugin/testData/box/configselector/crossModule.kt");
    }

    @Test
    @TestMetadata("generateHintsInFir.kt")
    public void testGenerateHintsInFir() {
      runTest("compiler-plugin/testData/box/configselector/generateHintsInFir.kt");
    }

    @Test
    @TestMetadata("generateHintsInIr.kt")
    public void testGenerateHintsInIr() {
      runTest("compiler-plugin/testData/box/configselector/generateHintsInIr.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/entry")
  @TestDataPath("$PROJECT_ROOT")
  public class Entry {
    @Test
    public void testAllFilesPresentInEntry() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/entry/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        runTest("compiler-plugin/testData/box/entry/activity/activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/entry/activity/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/entry/activity/crossModule.kt");
      }

      @Test
      @TestMetadata("customExternalParentScope.kt")
      public void testCustomExternalParentScope() {
        runTest("compiler-plugin/testData/box/entry/activity/customExternalParentScope.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/entry/activity/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("customParentScope.kt")
      public void testCustomParentScope() {
        runTest("compiler-plugin/testData/box/entry/activity/customParentScope.kt");
      }

      @Test
      @TestMetadata("customParentScopePositional.kt")
      public void testCustomParentScopePositional() {
        runTest("compiler-plugin/testData/box/entry/activity/customParentScopePositional.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/entry/activity/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("factoryContribution.kt")
      public void testFactoryContribution() {
        runTest("compiler-plugin/testData/box/entry/activity/factoryContribution.kt");
      }

      @Test
      @TestMetadata("fullFeatures.kt")
      public void testFullFeatures() {
        runTest("compiler-plugin/testData/box/entry/activity/fullFeatures.kt");
      }

      @Test
      @TestMetadata("mixEditorUseCase.kt")
      public void testMixEditorUseCase() {
        runTest("compiler-plugin/testData/box/entry/activity/mixEditorUseCase.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/entry/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/entry/page/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/entry/page/crossModule.kt");
      }

      @Test
      @TestMetadata("customExternalParentScope.kt")
      public void testCustomExternalParentScope() {
        runTest("compiler-plugin/testData/box/entry/page/customExternalParentScope.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/entry/page/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("customParentScope.kt")
      public void testCustomParentScope() {
        runTest("compiler-plugin/testData/box/entry/page/customParentScope.kt");
      }

      @Test
      @TestMetadata("customParentScopePositional.kt")
      public void testCustomParentScopePositional() {
        runTest("compiler-plugin/testData/box/entry/page/customParentScopePositional.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/entry/page/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("factoryContribution.kt")
      public void testFactoryContribution() {
        runTest("compiler-plugin/testData/box/entry/page/factoryContribution.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        runTest("compiler-plugin/testData/box/entry/page/paramPage.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/station")
  @TestDataPath("$PROJECT_ROOT")
  public class Station {
    @Test
    public void testAllFilesPresentInStation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        runTest("compiler-plugin/testData/box/station/activity/activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/station/activity/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/station/activity/crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/station/activity/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/station/activity/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        runTest("compiler-plugin/testData/box/station/activity/extraDependencies.kt");
      }

      @Test
      @TestMetadata("fullFeatures.kt")
      public void testFullFeatures() {
        runTest("compiler-plugin/testData/box/station/activity/fullFeatures.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/other")
    @TestDataPath("$PROJECT_ROOT")
    public class Other {
      @Test
      public void testAllFilesPresentInOther() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/other"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("broadcastReceiver.kt")
      public void testBroadcastReceiver() {
        runTest("compiler-plugin/testData/box/station/other/broadcastReceiver.kt");
      }

      @Test
      @TestMetadata("service.kt")
      public void testService() {
        runTest("compiler-plugin/testData/box/station/other/service.kt");
      }

      @Test
      @TestMetadata("worker.kt")
      public void testWorker() {
        runTest("compiler-plugin/testData/box/station/other/worker.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/station/page/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/station/page/crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/station/page/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/station/page/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        runTest("compiler-plugin/testData/box/station/page/extraDependencies.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        runTest("compiler-plugin/testData/box/station/page/paramPage.kt");
      }
    }
  }
}
