

package com.bandlab.metro.station.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.station.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/configselector")
  @TestDataPath("$PROJECT_ROOT")
  public class Configselector {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/box/configselector/" + fileName);
    }

    @Test
    public void testAllFilesPresentInConfigselector() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/configselector"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      run("basic.kt");
    }

    @Test
    @TestMetadata("crossModule.kt")
    public void testCrossModule() {
      run("crossModule.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/entry")
  @TestDataPath("$PROJECT_ROOT")
  public class Entry {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/box/entry/" + fileName);
    }

    @Test
    public void testAllFilesPresentInEntry() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/entry/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/box/entry/activity/" + fileName);
      }

      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        run("activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        run("crossModule.kt");
      }

      @Test
      @TestMetadata("customExternalParentScope.kt")
      public void testCustomExternalParentScope() {
        run("customExternalParentScope.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        run("customGraphMarker.kt");
      }

      @Test
      @TestMetadata("customParentScope.kt")
      public void testCustomParentScope() {
        run("customParentScope.kt");
      }

      @Test
      @TestMetadata("customParentScopePositional.kt")
      public void testCustomParentScopePositional() {
        run("customParentScopePositional.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        run("defaultDependencies.kt");
      }

      @Test
      @TestMetadata("fullFeatures.kt")
      public void testFullFeatures() {
        run("fullFeatures.kt");
      }

      @Test
      @TestMetadata("mixEditorUseCase.kt")
      public void testMixEditorUseCase() {
        run("mixEditorUseCase.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/entry/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/box/entry/page/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/entry/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        run("crossModule.kt");
      }

      @Test
      @TestMetadata("customExternalParentScope.kt")
      public void testCustomExternalParentScope() {
        run("customExternalParentScope.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        run("customGraphMarker.kt");
      }

      @Test
      @TestMetadata("customParentScope.kt")
      public void testCustomParentScope() {
        run("customParentScope.kt");
      }

      @Test
      @TestMetadata("customParentScopePositional.kt")
      public void testCustomParentScopePositional() {
        run("customParentScopePositional.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        run("defaultDependencies.kt");
      }

      @Test
      @TestMetadata("factoryContribution.kt")
      public void testFactoryContribution() {
        run("factoryContribution.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        run("paramPage.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/station")
  @TestDataPath("$PROJECT_ROOT")
  public class Station {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/box/station/" + fileName);
    }

    @Test
    public void testAllFilesPresentInStation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/box/station/activity/" + fileName);
      }

      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        run("activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        run("crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        run("customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        run("defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        run("extraDependencies.kt");
      }

      @Test
      @TestMetadata("fullFeatures.kt")
      public void testFullFeatures() {
        run("fullFeatures.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/other")
    @TestDataPath("$PROJECT_ROOT")
    public class Other {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/box/station/other/" + fileName);
      }

      @Test
      public void testAllFilesPresentInOther() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/other"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("broadcastReceiver.kt")
      public void testBroadcastReceiver() {
        run("broadcastReceiver.kt");
      }

      @Test
      @TestMetadata("service.kt")
      public void testService() {
        run("service.kt");
      }

      @Test
      @TestMetadata("worker.kt")
      public void testWorker() {
        run("worker.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/station/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/box/station/page/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/station/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        run("crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        run("customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        run("defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        run("extraDependencies.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        run("paramPage.kt");
      }
    }
  }
}
