

package com.bandlab.metro.station.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.station.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("internalConfigSelector.kt")
  public void testInternalConfigSelector() {
    runTest("compiler-plugin/testData/diagnostics/internalConfigSelector.kt");
  }

  @Test
  @TestMetadata("internalMetroStation.kt")
  public void testInternalMetroStation() {
    runTest("compiler-plugin/testData/diagnostics/internalMetroStation.kt");
  }

  @Test
  @TestMetadata("internalStationEntry.kt")
  public void testInternalStationEntry() {
    runTest("compiler-plugin/testData/diagnostics/internalStationEntry.kt");
  }

  @Test
  @TestMetadata("newStationEntryUseCase.kt")
  public void testNewStationEntryUseCase() {
    runTest("compiler-plugin/testData/diagnostics/newStationEntryUseCase.kt");
  }

  @Test
  @TestMetadata("pageMissingContext.kt")
  public void testPageMissingContext() {
    runTest("compiler-plugin/testData/diagnostics/pageMissingContext.kt");
  }

  @Test
  @TestMetadata("pageMissingExtraDependencies.kt")
  public void testPageMissingExtraDependencies() {
    runTest("compiler-plugin/testData/diagnostics/pageMissingExtraDependencies.kt");
  }

  @Test
  @TestMetadata("restrictedActivityParam.kt")
  public void testRestrictedActivityParam() {
    runTest("compiler-plugin/testData/diagnostics/restrictedActivityParam.kt");
  }

  @Test
  @TestMetadata("restrictedPageParam.kt")
  public void testRestrictedPageParam() {
    runTest("compiler-plugin/testData/diagnostics/restrictedPageParam.kt");
  }
}
