

package com.bandlab.metro.station.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.station.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("extraDependenciesMustBeVal.kt")
  public void testExtraDependenciesMustBeVal() {
    run("extraDependenciesMustBeVal.kt");
  }

  @Test
  @TestMetadata("extraDependenciesOnActivity.kt")
  public void testExtraDependenciesOnActivity() {
    run("extraDependenciesOnActivity.kt");
  }

  @Test
  @TestMetadata("internalConfigSelector.kt")
  public void testInternalConfigSelector() {
    run("internalConfigSelector.kt");
  }

  @Test
  @TestMetadata("internalMetroStation.kt")
  public void testInternalMetroStation() {
    run("internalMetroStation.kt");
  }

  @Test
  @TestMetadata("internalStationEntry.kt")
  public void testInternalStationEntry() {
    run("internalStationEntry.kt");
  }

  @Test
  @TestMetadata("newStationEntryUseCase.kt")
  public void testNewStationEntryUseCase() {
    run("newStationEntryUseCase.kt");
  }

  @Test
  @TestMetadata("pageMissingExtraDependencies.kt")
  public void testPageMissingExtraDependencies() {
    run("pageMissingExtraDependencies.kt");
  }

  @Test
  @TestMetadata("restrictedActivityParam.kt")
  public void testRestrictedActivityParam() {
    run("restrictedActivityParam.kt");
  }

  @Test
  @TestMetadata("restrictedPageParam.kt")
  public void testRestrictedPageParam() {
    run("restrictedPageParam.kt");
  }
}
