

package com.bandlab.metro.station.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.station.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/dump")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/dump/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/dump/configselector")
  @TestDataPath("$PROJECT_ROOT")
  public class Configselector {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/dump/configselector/" + fileName);
    }

    @Test
    public void testAllFilesPresentInConfigselector() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/configselector"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      run("basic.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/dump/entry")
  @TestDataPath("$PROJECT_ROOT")
  public class Entry {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/dump/entry/" + fileName);
    }

    @Test
    public void testAllFilesPresentInEntry() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/entry"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/dump/entry/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/dump/entry/activity/" + fileName);
      }

      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        run("activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/entry/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/dump/entry/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/dump/entry/page/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/entry/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        run("paramPage.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/dump/station")
  @TestDataPath("$PROJECT_ROOT")
  public class Station {
    private void run(String fileName) {
      runTest("compiler-plugin/testData/dump/station/" + fileName);
    }

    @Test
    public void testAllFilesPresentInStation() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/station"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/dump/station/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/dump/station/activity/" + fileName);
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/station/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/dump/station/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      private void run(String fileName) {
        runTest("compiler-plugin/testData/dump/station/page/" + fileName);
      }

      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/dump/station/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        run("basic.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        run("paramPage.kt");
      }
    }
  }
}
