package com.bandlab.metro.station

@Target(AnnotationTarget.FUNCTION)
@RequiresOptIn(
    level = RequiresOptIn.Level.ERROR,
    message = "This function will be generated by metro station, do not override it."
)
public annotation class GeneratedByMetroStation
