package com.bandlab.metro.station

import kotlin.reflect.KClass

/**
 * ## This annotation generates a Dependency Graph for the feature.
 *
 * Annotate your feature with [MetroStation], provide a dependency contract you need from the AppGraph,
 * and the compiler plugin will generate a standalone dependency graph for you ✨
 *
 * Usage:
 * ```kotlin
 * @MetroStation(appDependencies = MyPage.ServiceProvider::class)
 * class MyPage: Page<MyViewModel> {
 *
 *   @Composable
 *   override fun Content(viewModel: MyViewModel) {
 *     // MyViewModel is already injected at this point
 *     viewModel.appDependency
 *   }
 *
 *   interface ServiceProvider {
 *     val appDependency: AppDependency
 *   }
 * }
 * ```
 * Supported types: Page, Activity, Fragment, and any other classes
 *
 * ### Default Dependencies
 * We provide common default dependencies to ease the development for you.
 * - *Page*: DefaultPageDependencies.kt
 * - *Activity*: DefaultActivityDependencies.kt
 * - *Fragment*: DefaultFragmentDependencies.kt
 *
 * We also request some common app-level dependencies for you. For screens (page, activity, fragment), we extend `DefaultScreenServiceProvider` to the generated `FeatureServiceProvider` interface. For activities, we extend `CommonActivity.ServiceProvider` additionally.
 *
 * Besides the basic support, we will also generate param providers:
 * - For CommonActivity, param type declared as the generic type will be available in the graph.
 * - For ParamPage, we will provide both the initial param, and a flow of params that listens to the host activity's onNewIntent.
 *
 * ### Android Component Injection
 * We inject known Android components automatically for you:
 * - *Service*: The plugin injects `fun onCreate()` for you, if the `onCreate` is not declared, we will generate it and call `super.onCreate` after injection.
 * - *BroadcastReceiver*: The plugin injects `fun onReceive(context: Context, intent: Intent)` for you.
 * - *CoroutineWorker*: The plugin injects `suspend fun doWork(): Result` for you.
 *
 * ## Under the hood
 *
 * The compiler plugin will generate such FIR structures for you:
 * ```kotlin
 * class MyPage : Page<MyViewModel> {
 *
 *   // All code below will be generated by the compiler plugin:
 *   @GeneratedByMetroStation
 *   override fun injectViewModel(deps: PageGraphDependencies): MyViewModel {
 *     return createGraphAndInjectViewModel(
 *       deps = deps,
 *       param = Unit, // or the actual param type if you're using ParamPage
 *       factory = createGraphFactory<FeatureGraph.Factory>(),
 *       extraDependencies = ExtraDependencies,
 *     )
 *   }
 *
 *   @IROnlyFactories
 *   @PageScope
 *   @DependencyGraph(
 *     scope = MyPage::class,
 *     bindingContainers = [DefaultPageDependencies::class]
 *   )
 *   interface FeatureGraph : PageInjector<MyViewModel> {
 *
 *     @Provides
 *     fun provideBaseType(feature: MyPage): Page<*> = feature
 *
 *     @DependencyGraph.Factory
 *     interface Factory : PageGraphFactory<MyPage, MyViewModel, Unit, FeatureServiceProvider, EmptyExtraDependencies, FeatureGraph>
 *   }
 *
 *   @ContributesTo(AppScope::class)
 *   interface FeatureServiceProvider : ServiceProvider, DefaultScreenServiceProvider
 * }
 * ```
 *
 * If `extraDependencies` is presented, the FIR checker will request a param declared in the Page's constructor,
 * and the plugin will pass it while creating the graph.
 *
 * For classes extend `CommonActivity`, we will override the `inject` method like this:
 * ```kotlin
 * class MyActivity : CommonActivity<Unit>() {
 *   @GeneratedByMetroStation
 *   override fun inject() {
 *     createGraphFactory<FeatureGraph.Factory>()
 *       .create(this, applicationContext.resolveServiceProvider(), EmptyExtraDependencies)
 *       .injector
 *       .injectMembers(this)
 *   }
 * }
 * ```
 *
 * @param appDependencies The dependency contract you need the App graph to provide to your feature.
 * @param graphMarker A marker to aggregate a graph, default to the feature class itself (ex. MyPage).
 * @param extraDependencies External dependency contract you need from the parent Activity, only Page is supported.
 *
 * @see [dev.zacsweers.metro.DependencyGraph]
 */
@Target(AnnotationTarget.CLASS)
public annotation class MetroStation(
    val appDependencies: KClass<*>,
    val graphMarker: KClass<*> = Nothing::class,
    val extraDependencies: KClass<*> = Nothing::class,
)
