package com.bandlab.metro.station

import kotlin.reflect.KClass

/**
 * ## This annotation generates a Dependency Graph for the feature.
 *
 * Annotate your feature with [MetroStation], provide a dependency contract you need from the AppGraph,
 * and the compiler plugin will generate a standalone dependency graph for you ✨
 *
 * ```kotlin
 * @MetroStation(
 *   appDependencies = MyPage.ServiceProvider::class,
 *   extraDependencies = MyPage.ActivityDependencies::class
 * )
 * @Inject
 * class MyPage(
 *   context: Context,
 *   activityDependencies: ActivityDependencies
 * ): Page<MyViewModel> {
 *
 *   @Composable
 *   override fun Content(viewModel: MyViewModel) {
 *     // MyViewModel is already injected at this point
 *     viewModel.appDependency
 *     viewModel.activityScopedDependency
 *   }
 *
 *   interface ServiceProvider {
 *     val appDependency: AppDependency
 *   }
 *
 *   @Inject
 *   class ActivityDependencies(
 *     val activityScopedDependency: ActivityScopedDependency
 *   )
 * }
 * ```
 * Supported types: Page, Activity, Fragment, and any other classes
 *
 * ## Under the hood
 *
 * The compiler plugin will generate such FIR structures for you:
 * ```kotlin
 * // We will add a HasServiceProvider supertype
 * class MyPage(context: Context) : Page<MyViewModel>(), HasServiceProvider {
 *
 *   // All code below will be generated by the compiler plugin:
 *   private val graphCreator = lazy {
 *     graphCreator(
 *       context,
 *       createGraphFactory<FeatureGraph.Factory>(),
 *       EmptyExtraDependencies // Or actual extra dependencies if it's presented
 *     )
 *   }
 *
 *   override fun <T> resolve(): T = HasServiceProvider.resolveFrom(graphCreator.value)
 *
 *   @IROnlyFactories
 *   @PageScope
 *   @DependencyGraph(
 *     scope = MyPage::class,
 *     bindingContainers = [DefaultPageDependencies::class]
 *   )
 *   interface FeatureGraph : PageInjector<MyPage> {
 *
 *     @Provides
 *     fun provideBaseType(feature: MyPage): Page<*> = feature
 *
 *     @DependencyGraph.Factory
 *     interface Factory : PageGraphFactory<MyPage, FeatureServiceProvider, EmptyExtraDependencies, FeatureGraph>
 *   }
 *
 *   @ContributesTo(AppScope::class)
 *   interface FeatureServiceProvider : ServiceProvider, DefaultScreenServiceProvider
 * }
 * ```
 *
 * Besides the basic support, we will also generate param providers:
 * - For CommonActivity, param type T is available in the graph.
 * - For ParamPage, we will provide both the initial param, and a flow of params that listens to the host activity's onNewIntent.
 *
 * You'll need to provide either a Context or a ComponentActivity to the Page's primary constructor, and extra
 * dependencies if it's presented. They'll be used by the compiler during the IR phase.
 *
 * @param appDependencies The dependency contract you need the App graph to provide to your feature.
 * @param graphMarker A marker to aggregate a graph, default to the feature class itself (ex. MyPage).
 * @param extraDependencies External dependency contract that you need from other features.
 *
 * @see [dev.zacsweers.metro.DependencyGraph]
 */
@Target(AnnotationTarget.CLASS)
public annotation class MetroStation(
    val appDependencies: KClass<*>,
    val graphMarker: KClass<*> = Nothing::class,
    val extraDependencies: KClass<*> = Nothing::class,
)
