package com.bandlab.metro.station.extension

import com.bandlab.metro.station.graph.MetroStationIds
import com.bandlab.metro.station.utils.ClassIds
import com.bandlab.metro.station.utils.findMetroContributionSymbol
import com.bandlab.metro.station.utils.resolveParentScopeClassIdFromAnnotation
import com.fueledbycaffeine.autoservice.AutoService
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId

/**
 * Implements [MetroContributionExtension] to tell Metro's `ContributedInterfaceSupertypeGenerator`
 * about contributions from our generated `FeatureExtension.Factory` and `ExtensionFactoryContribution`
 * interfaces.
 *
 * This is necessary because Metro's predicate-based provider only discovers source declarations and
 * declarations generated by generators that registered the `@ContributesTo` predicate. Our
 * interfaces are generated by [StationEntryFir] (which registers a predicate for
 * `@StationEntry`), so Metro's in-compilation discovery doesn't see them.
 */
public class StationEntryContributionExtension(private val session: FirSession) : MetroContributionExtension {

    private val predicate = MetroStationIds.stationEntryPredicate

    private val annotatedClasses by lazy {
        session.predicateBasedProvider
            .getSymbolsByPredicate(predicate)
            .filterIsInstance<FirRegularClassSymbol>()
            .toList()
    }

    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(predicate)
    }

    override fun getContributions(
        scopeClassId: ClassId,
        typeResolverFactory: MetroFirTypeResolver.Factory,
    ): List<MetroContributionExtension.Contribution> {
        return annotatedClasses
            .filter { resolveParentScopeClassId(it) == scopeClassId }
            .flatMap { parentSymbol ->
                val factoryClassId = parentSymbol.classId
                    .createNestedClassId(MetroStationIds.featureExtensionName)
                    .createNestedClassId(MetroStationIds.nestedFactoryName)
                val extensionFactoryContributionClassId = parentSymbol.classId
                    .createNestedClassId(MetroStationIds.extensionFactoryContributionName)

                listOfNotNull(
                    resolveContribution(factoryClassId, factoryClassId),
                    resolveContribution(extensionFactoryContributionClassId, parentSymbol.classId),
                )
            }
    }

    private fun resolveParentScopeClassId(owner: FirRegularClassSymbol): ClassId {
        return resolveParentScopeClassIdFromAnnotation(
            owner,
            MetroStationIds.stationEntry,
            session,
            ClassIds.appScope
        )
    }

    private fun resolveContribution(
        contributionClassId: ClassId,
        originClassId: ClassId,
    ): MetroContributionExtension.Contribution? {
        val metroContributionSymbol = contributionClassId.findMetroContributionSymbol(session) ?: return null
        return MetroContributionExtension.Contribution(
            supertype = metroContributionSymbol.defaultType(),
            replaces = emptyList(),
            originClassId = originClassId,
        )
    }

    @AutoService
    public class Factory : MetroContributionExtension.Factory {
        override fun create(
            session: FirSession,
            options: MetroOptions,
            compatContext: CompatContext,
        ): MetroContributionExtension {
            return StationEntryContributionExtension(session)
        }
    }
}
