package com.bandlab.common.di

@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
@RequiresOptIn(
    // Use warning here so compiler tests can use it
    level = RequiresOptIn.Level.WARNING,
    message = "This function will be generated by metro station, do not override it or use it directly."
)
annotation class GeneratedByMetroStation
