package com.bandlab.common.di

@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
@RequiresOptIn(
    level = RequiresOptIn.Level.ERROR,
    message = "This function will be generated by metro station, do not override it or use it directly."
)
annotation class GeneratedByMetroStation
