

package com.bandlab.metro.extensions.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bandlab.metro.extensions.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/component")
  @TestDataPath("$PROJECT_ROOT")
  public class Component {
    @Test
    public void testAllFilesPresentInComponent() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/component"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/component/activity")
    @TestDataPath("$PROJECT_ROOT")
    public class Activity {
      @Test
      @TestMetadata("activityParam.kt")
      public void testActivityParam() {
        runTest("compiler-plugin/testData/box/component/activity/activityParam.kt");
      }

      @Test
      public void testAllFilesPresentInActivity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/component/activity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/component/activity/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/component/activity/crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/component/activity/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/component/activity/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        runTest("compiler-plugin/testData/box/component/activity/extraDependencies.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/box/component/page")
    @TestDataPath("$PROJECT_ROOT")
    public class Page {
      @Test
      public void testAllFilesPresentInPage() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/component/page"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("compiler-plugin/testData/box/component/page/basic.kt");
      }

      @Test
      @TestMetadata("crossModule.kt")
      public void testCrossModule() {
        runTest("compiler-plugin/testData/box/component/page/crossModule.kt");
      }

      @Test
      @TestMetadata("customGraphMarker.kt")
      public void testCustomGraphMarker() {
        runTest("compiler-plugin/testData/box/component/page/customGraphMarker.kt");
      }

      @Test
      @TestMetadata("defaultDependencies.kt")
      public void testDefaultDependencies() {
        runTest("compiler-plugin/testData/box/component/page/defaultDependencies.kt");
      }

      @Test
      @TestMetadata("extraDependencies.kt")
      public void testExtraDependencies() {
        runTest("compiler-plugin/testData/box/component/page/extraDependencies.kt");
      }

      @Test
      @TestMetadata("paramPage.kt")
      public void testParamPage() {
        runTest("compiler-plugin/testData/box/component/page/paramPage.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/configselector")
  @TestDataPath("$PROJECT_ROOT")
  public class Configselector {
    @Test
    public void testAllFilesPresentInConfigselector() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/configselector"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      runTest("compiler-plugin/testData/box/configselector/basic.kt");
    }

    @Test
    @TestMetadata("crossModule.kt")
    public void testCrossModule() {
      runTest("compiler-plugin/testData/box/configselector/crossModule.kt");
    }

    @Test
    @TestMetadata("generateHintsInFir.kt")
    public void testGenerateHintsInFir() {
      runTest("compiler-plugin/testData/box/configselector/generateHintsInFir.kt");
    }

    @Test
    @TestMetadata("generateHintsInIr.kt")
    public void testGenerateHintsInIr() {
      runTest("compiler-plugin/testData/box/configselector/generateHintsInIr.kt");
    }
  }
}
