on:
  pull_request: {}
  push:
    branches:
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build-compiler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 23

      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew check --continue --quiet

      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
  build-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 23

      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew -p samples check --continue --quiet
